# Generated by Django 4.2.30 on 2026-06-08 00:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Ученик'), ('editor', 'Редактор'), ('viewer', 'Наблюдатель'), ('public', 'Публичный доступ')], default='student', max_length=20, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Файл')),
                ('kind', models.CharField(choices=[('image', 'Картинка'), ('pdf', 'PDF'), ('graph', 'График'), ('source', 'Исходный файл'), ('attachment', 'Вложение'), ('student_work', 'Работа ученика')], default='image', max_length=20, verbose_name='Тип файла')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Необязательно. Краткое имя задачи.', max_length=300, verbose_name='Заголовок')),
                ('statement', models.TextField(help_text='Основной текст задачи. Можно использовать LaTeX-формулы.', verbose_name='Условие')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('solution', models.TextField(blank=True, verbose_name='Решение (необязательно)')),
                ('problem_type', models.CharField(blank=True, max_length=120, verbose_name='Тип задачи')),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сложность (1–5)')),
                ('difficulty_native', models.CharField(blank=True, help_text='Например: *, **, ***', max_length=20, verbose_name='Сложность (метка источника)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('needs_review', 'На проверку'), ('published', 'Опубликована'), ('archived', 'В архиве'), ('hidden', 'Скрыта'), ('duplicate', 'Дубликат')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('files', models.ManyToManyField(blank=True, related_name='problems', to='problems.fileasset', verbose_name='Файлы')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_problems', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='Автор / составитель')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('kind', models.CharField(blank=True, help_text='Например: задачник, олимпиада, сборник', max_length=100, verbose_name='Тип источника')),
                ('note', models.TextField(blank=True, verbose_name='Заметка об авторских правах')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Короткий код')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Короткий код (для ссылок)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Короткий код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='problems.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Подтема',
                'verbose_name_plural': 'Подтемы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=120, verbose_name='Этап олимпиады')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Класс')),
                ('problem_number', models.CharField(blank=True, max_length=50, verbose_name='Номер задачи в источнике')),
                ('page', models.CharField(blank=True, max_length=50, verbose_name='Страница')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Заметка')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='problems.problem', verbose_name='Задача')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='problems.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Привязка к источнику',
                'verbose_name_plural': 'Привязки к источникам',
            },
        ),
        migrations.CreateModel(
            name='ProblemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок содержимого')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Что изменилось')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Версия задачи',
                'verbose_name_plural': 'Версии задач',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ProblemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например: а, б, в', max_length=10, verbose_name='Метка пункта')),
                ('statement', models.TextField(blank=True, verbose_name='Условие пункта')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('solution', models.TextField(blank=True, verbose_name='Решение (необязательно)')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Баллы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Подпункт',
                'verbose_name_plural': 'Подпункты',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='subtopics',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.subtopic', verbose_name='Подтемы'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='problem',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.topic', verbose_name='Темы'),
        ),
    ]
