# Generated by Django 4.2.30 on 2026-06-08 00:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('topics', models.ManyToManyField(blank=True, related_name='mistake_tags', to='problems.topic', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Типичная ошибка',
                'verbose_name_plural': 'Типичные ошибки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Критерии оценивания', max_length=200, verbose_name='Название рубрики')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('topics', models.ManyToManyField(blank=True, related_name='skills', to='problems.topic', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TheoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('body', models.TextField(help_text='Можно использовать LaTeX-формулы.', verbose_name='Текст (определения, формулы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('mistakes', models.ManyToManyField(blank=True, related_name='theory_pages', to='problems.mistaketag', verbose_name='Типичные ошибки')),
                ('problems', models.ManyToManyField(blank=True, related_name='theory_pages', to='problems.problem', verbose_name='Связанные задачи')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_pages', to='problems.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Страница теории',
                'verbose_name_plural': 'Страницы теории',
                'ordering': ['topic', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Критерий')),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Максимальный балл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='problems.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст подсказки')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problempart', verbose_name='Подпункт')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Подсказка',
                'verbose_name_plural': 'Подсказки',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='mistakes',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.mistaketag', verbose_name='Типичные ошибки'),
        ),
        migrations.AddField(
            model_name='problem',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.skill', verbose_name='Навыки'),
        ),
        migrations.CreateModel(
            name='StudentSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень (0–100)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='problems.skill', verbose_name='Навык')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс по навыку',
                'verbose_name_plural': 'Прогресс по навыкам',
                'ordering': ['student', 'skill'],
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
