# Generated by Django 4.2.30 on 2026-06-08 00:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_mistaketag_rubric_skill_theorypage_rubriccriterion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Домашка / назначение',
                'verbose_name_plural': 'Домашки / назначения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField(blank=True, verbose_name='Текст решения')),
                ('solution_file', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/', verbose_name='Прикреплённый файл')),
                ('submitted_answer', models.TextField(blank=True, verbose_name='Отправленный ответ')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('submitted', 'Отправлено'), ('reviewed', 'Проверено')], default='not_started', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.assignment', verbose_name='Домашка')),
                ('opened_hints', models.ManyToManyField(blank=True, related_name='opened_in', to='problems.hint', verbose_name='Открытые подсказки')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='Задача')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Решение ученика',
                'verbose_name_plural': 'Решения учеников',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'assignment', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Балл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('mistakes', models.ManyToManyField(blank=True, related_name='feedbacks', to='problems.mistaketag', verbose_name='Отмеченные ошибки')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='problems.submission', verbose_name='Решение ученика')),
            ],
            options={
                'verbose_name': 'Проверка преподавателя',
                'verbose_name_plural': 'Проверки преподавателя',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название занятия')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата занятия')),
                ('goals', models.TextField(blank=True, verbose_name='Цели занятия')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Тайминг (минут)')),
                ('warm_up', models.TextField(blank=True, verbose_name='Разминка (warm-up)')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Заметки преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('challenge_problems', models.ManyToManyField(blank=True, related_name='lessons_as_challenge', to='problems.problem', verbose_name='Задачи-вызов (challenge)')),
                ('homework_problems', models.ManyToManyField(blank=True, related_name='lessons_as_homework', to='problems.problem', verbose_name='Домашние задачи')),
                ('main_problems', models.ManyToManyField(blank=True, related_name='lessons_as_main', to='problems.problem', verbose_name='Основные задачи')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='problems.lesson', verbose_name='Занятие'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='problems.problem', verbose_name='Задачи'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='assignments_received', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень (0–100)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='problems.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Прогресс по теме',
                'verbose_name_plural': 'Прогресс по темам',
                'ordering': ['student', 'topic'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
