# Generated by Django 4.2.30 on 2026-06-08 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_assignment_submission_teacherfeedback_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('preamble', models.TextField(blank=True, help_text='Всё, что идёт между \\documentclass{} и \\begin{document}.', verbose_name='Преамбула LaTeX')),
                ('header', models.TextField(blank=True, verbose_name='Заголовок документа')),
                ('margin_top', models.DecimalField(decimal_places=1, default=2.5, max_digits=4, verbose_name='Верхнее поле (см)')),
                ('margin_bottom', models.DecimalField(decimal_places=1, default=2.5, max_digits=4, verbose_name='Нижнее поле (см)')),
                ('margin_left', models.DecimalField(decimal_places=1, default=2.0, max_digits=4, verbose_name='Левое поле (см)')),
                ('margin_right', models.DecimalField(decimal_places=1, default=2.0, max_digits=4, verbose_name='Правое поле (см)')),
                ('font_size', models.PositiveSmallIntegerField(default=12, verbose_name='Размер шрифта (пт)')),
                ('numbering_style', models.CharField(blank=True, help_text='Например: «Задача N» или «№N»', max_length=100, verbose_name='Стиль нумерации')),
                ('show_answers', models.BooleanField(default=False, verbose_name='Показывать ответы')),
                ('show_solutions', models.BooleanField(default=False, verbose_name='Показывать решения')),
                ('preview_html', models.TextField(blank=True, verbose_name='HTML-превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Шаблон экспорта',
                'verbose_name_plural': 'Шаблоны экспорта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('import', 'Импорт'), ('export', 'Экспорт'), ('ai_enrich', 'AI-обогащение'), ('dedup', 'Дедупликация'), ('backup', 'Резервная копия')], max_length=20, verbose_name='Тип задачи')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('done', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил')),
            ],
            options={
                'verbose_name': 'Фоновая задача',
                'verbose_name_plural': 'Фоновые задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='Исходный файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('done', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='Импортировано задач')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='problems.job', verbose_name='Фоновая задача')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='problems.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Сессия импорта',
                'verbose_name_plural': 'Сессии импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('json', 'JSON'), ('markdown', 'Markdown'), ('docx', 'DOCX'), ('zip', 'ZIP-архив'), ('tex', 'LaTeX (.tex)'), ('pdf', 'PDF')], max_length=20, verbose_name='Формат')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/', verbose_name='Файл-результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_records', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_records', to='problems.job', verbose_name='Фоновая задача')),
            ],
            options={
                'verbose_name': 'Запись об экспорте',
                'verbose_name_plural': 'Записи об экспортах',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('problems', models.ManyToManyField(blank=True, related_name='collections', to='problems.problem', verbose_name='Задачи')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['-created_at'],
            },
        ),
    ]
