# Generated by Django 4.2.30 on 2026-06-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_template_job_importsession_exportrecord_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Автоматически для дедупликации при импорте.', max_length=32, verbose_name='MD5-хэш условия'),
        ),
    ]
