# Generated by Django 4.2.30 on 2026-06-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
