# Generated by Django 4.2.30 on 2026-06-08 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_embedding_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(verbose_name='Сходство (0–1)')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('confirmed', 'Подтверждён дубль'), ('rejected', 'Не дубль')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Найдено')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('problem_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_as_a', to='problems.problem', verbose_name='Задача A')),
                ('problem_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_as_b', to='problems.problem', verbose_name='Задача B')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicates', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Кандидат на дубликат',
                'verbose_name_plural': 'Кандидаты на дубликаты',
                'ordering': ['-similarity'],
                'unique_together': {('problem_a', 'problem_b')},
            },
        ),
    ]
