# Generated by Django 4.2.30 on 2026-06-08 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_duplicate_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesmosGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('state', models.JSONField(verbose_name='Состояние графика (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desmos_graphs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'График Desmos',
                'verbose_name_plural': 'Графики Desmos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
