# Generated by Django 4.2.30 on 2026-06-09 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_desmosgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='problems.problem', verbose_name='Возможный дубликат задачи'),
        ),
    ]
