# Generated by Django 4.2.30 on 2026-06-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_duplicate_of_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='similar_problems',
            field=models.ManyToManyField(blank=True, related_name='similar_to', to='problems.problem'),
        ),
    ]
