# Generated by Django 4.2.30 on 2026-06-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_similar_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='problem_order',
            field=models.JSONField(default=list, verbose_name='Порядок задач'),
        ),
        migrations.AddField(
            model_name='collection',
            name='template_type',
            field=models.CharField(choices=[('homework', 'Домашнее задание'), ('test', 'Контрольная работа'), ('sheet', 'Листок задач')], default='homework', max_length=20, verbose_name='Тип подборки'),
        ),
        migrations.AddField(
            model_name='collection',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True, verbose_name='Токен'),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменена'),
        ),
    ]
