# Generated by Django 4.2.30 on 2026-06-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_calendarevent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='needs_quality_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Скрыта из каталога качественным шлюзом (битый рендер формул)', verbose_name='Требует проверки качества'),
        ),
    ]
