# Generated by Django 4.2.30 on 2026-06-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_problem_needs_quality_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_needs_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Кнопка «Показать решение» скрыта (битый рендер решения)', verbose_name='Решение требует проверки'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='needs_quality_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Скрыта из каталога качественным шлюзом (битый рендер условия)', verbose_name='Требует проверки качества'),
        ),
    ]
