# Generated by Django 4.2.30 on 2026-06-12 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_problem_solution_needs_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTopicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbor_votes', models.PositiveSmallIntegerField(default=0, verbose_name='Голосов соседей (из 10)')),
                ('mean_similarity', models.FloatField(default=0.0, verbose_name='Средняя близость соседей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначено')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_topic_assignments', to='problems.problem', verbose_name='Задача')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_assignments', to='problems.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Автоназначение темы',
                'verbose_name_plural': 'Автоназначения тем',
                'unique_together': {('problem', 'topic')},
            },
        ),
    ]
