# Generated by Django 4.2.30 on 2026-06-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_autotopicassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ai_blurb',
            field=models.TextField(blank=True, default='', help_text='ИИ: Дано/Найти или суть (внутреннее, для поискового отпечатка; на сайте не показывается)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='multiple_problems',
            field=models.BooleanField(default=False, help_text='ИИ-флаг: задача содержит несколько условий, требует ручного разбиения.', verbose_name='Склейка нескольких задач'),
        ),
    ]
