# Generated by Django 4.2.30 on 2026-07-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_batch1_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_ai_extracted',
            field=models.BooleanField(default=False, help_text='Батч 2: решение вынесено из текста задачи автоматически, требует проверки.', verbose_name='Решение извлечено ИИ'),
        ),
    ]
