# Generated by Django 4.2.30 on 2026-07-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_add_solution_ai_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcereference',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
