# Generated by Django 4.2.30 on 2026-07-21 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_sourcereference_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('perfect', 'Идеально'), ('broken_formula', 'Сломанная формула'), ('bare_math', 'Голая математика / $'), ('merged_structure', 'Слипшийся список или структура'), ('leaked_solution', 'Утёкшее «Решение:/Ответ:»'), ('junk', 'Мусор (колонтитулы, номера страниц, обрубки)'), ('broken_table', 'Развалившаяся таблица'), ('other', 'Прочее (с комментарием)'), ('disputed', 'Спорно')], max_length=32, verbose_name='Категория')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('reviewer', models.CharField(blank=True, max_length=64, verbose_name='Ревьюер')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда вынесен')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_verdicts', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Вердикт ревью',
                'verbose_name_plural': 'Вердикты ревью',
            },
        ),
        migrations.AddConstraint(
            model_name='reviewverdict',
            constraint=models.UniqueConstraint(fields=('problem', 'reviewer'), name='uniq_review_verdict_per_reviewer'),
        ),
    ]
