# Generated by Django 4.2.30 on 2026-07-28 19:08
"""Вердикты ревью: пакет в ключе + множественный выбор категорий.

Уникальность (problem, reviewer) → (bundle, problem, category): у задачи может
быть несколько дефектов сразу, и это несколько строк, а не одна.

Проставление пакета существующим строкам — не косметика, а условие
идемпотентности: все 2 401 вердикта пришли из пакета ile_20260721, и без
проставленного bundle повторный импорт того же файла (в нём bundle_id есть)
создал бы 2 401 дубль вместо обновления. Тексты вердиктов не меняются.
"""

from django.db import migrations, models

# Пакет, из которого приехали все существующие вердикты (проверено: 2 401
# строка, ревьюер один, все id входят в манифест этого пакета).
LEGACY_BUNDLE = 'ile_20260721'


def set_legacy_bundle(apps, schema_editor):
    ReviewVerdict = apps.get_model('problems', 'ReviewVerdict')
    ReviewVerdict.objects.filter(bundle='').update(bundle=LEGACY_BUNDLE)


def unset_legacy_bundle(apps, schema_editor):
    ReviewVerdict = apps.get_model('problems', 'ReviewVerdict')
    ReviewVerdict.objects.filter(bundle=LEGACY_BUNDLE).update(bundle='')


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_reviewverdict_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewverdict',
            name='uniq_review_verdict_per_reviewer',
        ),
        migrations.AddField(
            model_name='reviewverdict',
            name='bundle',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Пакет'),
        ),
        migrations.RunPython(set_legacy_bundle, unset_legacy_bundle),
        migrations.AlterField(
            model_name='reviewverdict',
            name='category',
            field=models.CharField(choices=[('perfect', 'Идеально'), ('broken_formula', 'Сломанная формула'), ('bare_math', 'Голая математика / $'), ('merged_structure', 'Слипшийся список или структура'), ('leaked_solution', 'Утёкшее «Решение:/Ответ:»'), ('junk', 'Мусор (колонтитулы, номера страниц, обрубки)'), ('broken_table', 'Развалившаяся таблица'), ('other', 'Прочее (с комментарием)'), ('disputed', 'Спорно'), ('trash', 'Гагно')], max_length=32, verbose_name='Категория'),
        ),
        migrations.AddConstraint(
            model_name='reviewverdict',
            constraint=models.UniqueConstraint(fields=('bundle', 'problem', 'category'), name='uniq_review_verdict_per_category'),
        ),
    ]
