# Generated by Django 4.2.30 on 2026-08-04 00:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_reviewverdict_bundle_multicategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_draft', models.TextField(blank=True, verbose_name='Черновик ответа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сохранён')),
            ],
            options={
                'verbose_name': 'Черновик ответа',
                'verbose_name_plural': 'Черновики ответов',
            },
        ),
        migrations.CreateModel(
            name='AssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Балл')),
                ('solution_override', models.TextField(blank=True, verbose_name='Своё решение')),
                ('solution_steps', models.JSONField(blank=True, null=True, verbose_name='Шаги решения')),
                ('solution_visible_after', models.CharField(choices=[('deadline', 'После дедлайна'), ('submit', 'Сразу после сдачи'), ('manual', 'Вручную'), ('never', 'Никогда')], default='deadline', max_length=16, verbose_name='Когда показать решение')),
                ('solution_released_at', models.DateTimeField(blank=True, null=True, verbose_name='Открыто вручную')),
            ],
            options={
                'verbose_name': 'Задача в домашке',
                'verbose_name_plural': 'Задачи в домашке',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Необязательно.', max_length=300, verbose_name='Название')),
                ('statement', models.TextField(help_text='Формулы в долларах: $Q_d = 100 - P$. Рендерит KaTeX.', verbose_name='Условие')),
                ('kind', models.CharField(choices=[('open', 'Открытая задача'), ('tf', 'Верно / неверно'), ('single', 'Один верный вариант'), ('multiple', 'Несколько верных вариантов')], default='open', max_length=16, verbose_name='Тип')),
                ('correct_answer', models.TextField(blank=True, verbose_name='Правильный ответ')),
                ('answer_tolerance', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Допуск')),
                ('solution', models.TextField(blank=True, verbose_name='Эталонное решение')),
                ('solution_steps', models.JSONField(blank=True, null=True, verbose_name='Шаги решения')),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность (1–5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена')),
            ],
            options={
                'verbose_name': 'Своя задача репетитора',
                'verbose_name_plural': 'Свои задачи репетиторов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomProblemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Сдана')),
                ('is_auto_submitted', models.BooleanField(default=False, verbose_name='Сдана автоматически')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Попытка контрольной',
                'verbose_name_plural': 'Попытки контрольных',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Ключ сессии')),
                ('source', models.CharField(choices=[('catalog', 'Каталог'), ('homework', 'Домашка'), ('exam', 'Контрольная'), ('game', 'Игра')], max_length=16, verbose_name='Откуда')),
                ('event_type', models.CharField(choices=[('opened', 'Открыл'), ('attempted', 'Попытался'), ('solved', 'Решил верно'), ('failed', 'Ошибся'), ('hint_used', 'Открыл подсказку'), ('skipped', 'Пропустил')], max_length=16, verbose_name='Событие')),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сложность')),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Секунд потрачено')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Учебное событие',
                'verbose_name_plural': 'Учебные события',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('visibility', models.CharField(choices=[('group', 'Видят все в группе'), ('private', 'Только репетитор и автор')], default='group', max_length=16, verbose_name='Видимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
            ],
            options={
                'verbose_name': 'Комментарий к задаче',
                'verbose_name_plural': 'Комментарии к задачам',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('kind', models.CharField(choices=[('problems', 'Задачи'), ('graphs', 'Графики')], default='problems', max_length=16, verbose_name='Для чего')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Папка сохранённого',
                'verbose_name_plural': 'Папки сохранённого',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('scene', models.JSONField(blank=True, default=dict, verbose_name='Сцена калькулятора')),
                ('preview', models.CharField(blank=True, max_length=500, verbose_name='Превью (путь)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
            ],
            options={
                'verbose_name': 'Сохранённый график',
                'verbose_name_plural': 'Сохранённые графики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сохранена')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена')),
            ],
            options={
                'verbose_name': 'Сохранённая задача',
                'verbose_name_plural': 'Сохранённые задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tutor', 'Репетитор'), ('student', 'Ученик'), ('parent', 'Родитель')], default='student', max_length=16, verbose_name='Роль')),
                ('grade', models.PositiveSmallIntegerField(blank=True, help_text='5–11, необязательно.', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(11)], verbose_name='Класс')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='Школа')),
                ('phone', models.CharField(blank=True, help_text='Необязательно.', max_length=32, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сдать до'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит времени (минут)'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец окна'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='exam_mode',
            field=models.CharField(blank=True, choices=[('window', 'Окно (все одновременно)'), ('limit', 'Дедлайн с лимитом времени')], max_length=16, null=True, verbose_name='Режим контрольной'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='problems.studentgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='kind',
            field=models.CharField(choices=[('homework', 'Домашка'), ('exam', 'Контрольная')], default='homework', max_length=16, verbose_name='Тип работы'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='show_results_immediately',
            field=models.BooleanField(default=True, help_text='Тесты проверяются автоматически; на контрольной результат иногда лучше придержать до проверки открытых задач.', verbose_name='Показывать результат сразу'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало окна'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.assignmentitem', verbose_name='Задача в домашке'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('problem_item__isnull', False)), fields=('student', 'problem_item'), name='uniq_submission_per_item'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='savedproblem',
            name='catalog_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='problems.problem', verbose_name='Задача каталога'),
        ),
        migrations.AddField(
            model_name='savedproblem',
            name='custom_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='problems.customproblem', verbose_name='Своя задача'),
        ),
        migrations.AddField(
            model_name='savedproblem',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.savedfolder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='savedproblem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_problems', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='savedgraph',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphs', to='problems.savedfolder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='savedgraph',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_graphs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='savedfolder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_folders', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_comments', to='problems.assignment', verbose_name='Домашка'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='problem_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.assignmentitem', verbose_name='Задача в домашке'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_comments_received', to=settings.AUTH_USER_MODEL, verbose_name='Адресат'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='problems.assignment', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='catalog_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='problems.problem', verbose_name='Задача каталога'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='custom_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='problems.customproblem', verbose_name='Своя задача'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to='problems.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='problems.assignment', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='customproblemoption',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='problems.customproblem', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='customproblem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_problems', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='customproblem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_problems', to='problems.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='assignmentitem',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='problems.assignment', verbose_name='Домашка'),
        ),
        migrations.AddField(
            model_name='assignmentitem',
            name='catalog_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_items', to='problems.problem', verbose_name='Задача каталога'),
        ),
        migrations.AddField(
            model_name='assignmentitem',
            name='custom_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_items', to='problems.customproblem', verbose_name='Своя задача'),
        ),
        migrations.AddField(
            model_name='answerdraft',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='problems.examattempt', verbose_name='Попытка'),
        ),
        migrations.AddField(
            model_name='answerdraft',
            name='problem_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='problems.assignmentitem', verbose_name='Задача в домашке'),
        ),
        migrations.AddConstraint(
            model_name='savedproblem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('catalog_problem__isnull', False), ('custom_problem__isnull', True)), models.Q(('catalog_problem__isnull', True), ('custom_problem__isnull', False)), _connector='OR'), name='saved_problem_exactly_one_problem'),
        ),
        migrations.AddConstraint(
            model_name='savedproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('catalog_problem__isnull', False)), fields=('owner', 'catalog_problem'), name='uniq_saved_catalog_problem'),
        ),
        migrations.AddConstraint(
            model_name='savedproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_problem__isnull', False)), fields=('owner', 'custom_problem'), name='uniq_saved_custom_problem'),
        ),
        migrations.AddIndex(
            model_name='savedgraph',
            index=models.Index(fields=['owner', '-created_at'], name='idx_savedgraph_owner'),
        ),
        migrations.AddConstraint(
            model_name='savedfolder',
            constraint=models.UniqueConstraint(fields=('owner', 'kind', 'name'), name='uniq_saved_folder_name'),
        ),
        migrations.AddIndex(
            model_name='problemcomment',
            index=models.Index(fields=['assignment', 'problem_item'], name='idx_comment_assign_item'),
        ),
        migrations.AddIndex(
            model_name='problemcomment',
            index=models.Index(fields=['author', 'created_at'], name='idx_comment_author_date'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', '-created_at'], name='idx_event_user_date'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', 'topic'], name='idx_event_user_topic'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['source', '-created_at'], name='idx_event_source_date'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='uniq_exam_attempt'),
        ),
        migrations.AddIndex(
            model_name='customproblem',
            index=models.Index(fields=['owner', '-created_at'], name='idx_customprob_owner'),
        ),
        migrations.AddConstraint(
            model_name='assignmentitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('catalog_problem__isnull', False), ('custom_problem__isnull', True)), models.Q(('catalog_problem__isnull', True), ('custom_problem__isnull', False)), _connector='OR'), name='assignment_item_exactly_one_problem'),
        ),
        migrations.AddConstraint(
            model_name='answerdraft',
            constraint=models.UniqueConstraint(fields=('attempt', 'problem_item'), name='uniq_answer_draft'),
        ),
    ]
