# Generated by Django 4.2.30 on 2026-08-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_answerdraft_assignmentitem_customproblem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
