# Generated by Django 4.2.30 on 2026-08-04 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0024_studentgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentitem',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_items', to='problems.savedgraph', verbose_name='График'),
        ),
    ]
