# Generated by Django 4.2.30 on 2026-08-04 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def move_due_at_to_deadline(apps, schema_editor):
    """Фаза 0.3: срок сдачи переезжает в единственное поле `deadline`.

    Полей срока было два, и экраны спрашивали разные — список ученика писал
    «без срока» у контрольной, у которой срок задан в `due_at`. Переносим
    только туда, где `deadline` пуст: заполненный `deadline` главнее, его
    выставил человек.
    """
    Assignment = apps.get_model('problems', 'Assignment')
    moved = 0
    for assignment in Assignment.objects.filter(
            due_at__isnull=False, deadline__isnull=True).iterator():
        assignment.deadline = assignment.due_at
        assignment.save(update_fields=['deadline'])
        moved += 1
    if moved:
        print('  перенесено сроков due_at -> deadline: %d' % moved)


def unmove_due_at(apps, schema_editor):
    """Обратный ход намеренно ПУСТОЙ.

    Разделить обратно нельзя: после переезда неизвестно, какой `deadline`
    был исходным, а какой приехал из `due_at`. Данные при откате не теряются
    (`due_at` не очищается), просто не разъезжаются заново.
    """
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0025_assignmentitem_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(max_length=300, verbose_name='Условие получения')),
                ('icon', models.CharField(default='🏅', max_length=8, verbose_name='Значок')),
                ('category', models.CharField(choices=[('depth', 'Глубина'), ('consistency', 'Постоянство'), ('skill', 'Мастерство'), ('milestone', 'Веха')], default='milestone', max_length=16, verbose_name='Категория')),
                ('condition', models.JSONField(default=dict, verbose_name='Условие (машинное)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='answerdraft',
            name='solution_draft',
            field=models.TextField(blank=True, verbose_name='Черновик решения'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='leaderboard_enabled',
            field=models.BooleanField(default=False, help_text='Ученик увидит топ-3 и своё место. Полный список с аутсайдерами не показывается никогда.', verbose_name='Показывать рейтинг в группе'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='attempted',
            field=models.PositiveIntegerField(default=0, verbose_name='Попыток'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='mastery_level',
            field=models.CharField(choices=[('none', 'Не начата'), ('familiar', 'Знаком'), ('confident', 'Уверенно'), ('mastered', 'Разобрался')], default='none', max_length=16, verbose_name='Владение'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='solved',
            field=models.PositiveIntegerField(default=0, verbose_name='Решено верно'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='solved_hard',
            field=models.PositiveIntegerField(default=0, verbose_name='Из них сложных'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сдать до (устарело)'),
        ),
        migrations.CreateModel(
            name='StudentProgressProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0, verbose_name='Всего опыта')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Серия дней')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='Последний зачтённый день')),
                ('freezes_available', models.PositiveSmallIntegerField(default=2, verbose_name='Заморозок осталось')),
                ('freezes_used_this_month', models.PositiveSmallIntegerField(default=0, verbose_name='Заморозок потрачено в этом месяце')),
                ('freezes_period', models.DateField(blank=True, null=True, verbose_name='Месяц заморозок')),
                ('weekly_goal', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Цель на неделю (задач)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_profile', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс ученика',
                'verbose_name_plural': 'Прогресс учеников',
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('best_correct_streak', 'Верных подряд'), ('hardest_solved', 'Самая сложная решённая'), ('most_productive_day', 'Лучший день'), ('fastest_homework', 'Быстрее всего сдал домашку')], max_length=32, verbose_name='Вид')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('achieved_at', models.DateTimeField(auto_now=True, verbose_name='Когда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Личный рекорд',
                'verbose_name_plural': 'Личные рекорды',
                'ordering': ['user', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_links_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто связал')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Связь родитель — ребёнок',
                'verbose_name_plural': 'Связи родитель — ребёнок',
                'ordering': ['parent', 'student'],
            },
        ),
        migrations.CreateModel(
            name='EarnedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='problems.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Полученное достижение',
                'verbose_name_plural': 'Полученные достижения',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='День')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='Опыта за день')),
                ('problems_attempted', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('problems_solved', models.PositiveIntegerField(default=0, verbose_name='Решено верно')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Секунд')),
                ('counted_for_streak', models.BooleanField(default=False, verbose_name='Зачтён в серию')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Дневная сводка',
                'verbose_name_plural': 'Дневные сводки',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='personalrecord',
            constraint=models.UniqueConstraint(fields=('user', 'kind'), name='uniq_personal_record'),
        ),
        migrations.AddConstraint(
            model_name='parentlink',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='uniq_parent_student'),
        ),
        migrations.AddConstraint(
            model_name='earnedachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='uniq_earned_achievement'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['user', 'date'], name='idx_daily_user_date'),
        ),
        migrations.AddConstraint(
            model_name='dailysummary',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily_summary'),
        ),
        migrations.RunPython(move_due_at_to_deadline, unmove_due_at),
    ]
