# Generated by Django 4.2.30 on 2026-08-05 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0026_stats_gamification_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верно')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Балл за пункт')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Максимум за пункт')),
            ],
            options={
                'verbose_name': 'Ответ на пункт',
                'verbose_name_plural': 'Ответы на пункты',
                'ordering': ['part__order', 'part__label', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='answerdraft',
            name='uniq_answer_draft',
        ),
        migrations.AddField(
            model_name='answerdraft',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='problems.problempart', verbose_name='Пункт'),
        ),
        migrations.AddConstraint(
            model_name='answerdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('part__isnull', False)), fields=('attempt', 'problem_item', 'part'), name='uniq_answer_draft_part'),
        ),
        migrations.AddConstraint(
            model_name='answerdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('part__isnull', True)), fields=('attempt', 'problem_item'), name='uniq_answer_draft_whole'),
        ),
        migrations.AddField(
            model_name='partanswer',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='problems.problempart', verbose_name='Пункт'),
        ),
        migrations.AddField(
            model_name='partanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_answers', to='problems.submission', verbose_name='Решение'),
        ),
        migrations.AddConstraint(
            model_name='partanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('part__isnull', False)), fields=('submission', 'part'), name='uniq_part_answer_part'),
        ),
        migrations.AddConstraint(
            model_name='partanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('part__isnull', True)), fields=('submission',), name='uniq_part_answer_whole'),
        ),
    ]
