# Generated by Django 4.2.30 on 2026-08-05 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_partanswer_remove_answerdraft_uniq_answer_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к работе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_feedback', to='problems.assignment', verbose_name='Работа')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_feedback_written', to=settings.AUTH_USER_MODEL, verbose_name='Написал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Комментарий к работе',
                'verbose_name_plural': 'Комментарии к работам',
            },
        ),
        migrations.AddConstraint(
            model_name='workfeedback',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='uniq_work_feedback'),
        ),
    ]
