# Generated by Django 4.2.30 on 2026-08-06 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0028_workfeedback_workfeedback_uniq_work_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='homework_plan', max_length=40, verbose_name='Что делали')),
                ('model_name', models.CharField(max_length=80, verbose_name='Модель')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Токенов на входе')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Токенов на выходе')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Стоимость, $')),
                ('ok', models.BooleanField(default=True, verbose_name='Успешно')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Расход на ИИ',
                'verbose_name_plural': 'Расходы на ИИ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='problems_ai_user_id_c72cab_idx')],
            },
        ),
    ]
