# Generated by Django 4.2.30 on 2026-08-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0029_aiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentitem',
            name='answer_override',
            field=models.JSONField(blank=True, null=True, verbose_name='Утверждённые ответы'),
        ),
    ]
