# Generated by Django 4.2.30 on 2026-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0030_assignment_item_answer_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='cache_read_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Токенов прочитано из кэша'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='cache_write_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='Токенов записано в кэш'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='provider',
            field=models.CharField(blank=True, max_length=40, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='seconds',
            field=models.FloatField(default=0, verbose_name='Секунд'),
        ),
    ]
