# Generated by Django 4.2.30 on 2026-08-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0032_assignment_item_points_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='partanswer',
            name='auto_zero',
            field=models.BooleanField(default=False, verbose_name='Ноль автоматом за пустоту'),
        ),
    ]
