# Generated by Django 4.2.30 on 2026-08-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0033_partanswer_auto_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='manual_order',
            field=models.BooleanField(default=False, help_text='Не перестраивать задачи «сначала тесты, потом задачи».', verbose_name='Порядок задан вручную'),
        ),
    ]
