# Generated by Django 4.2.30 on 2026-08-10 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0035_comment_visibility_self'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(help_text='1 — легко, 10 — очень сложно.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_votes', to='problems.assignment', verbose_name='Работа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_difficulty_votes', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оценка сложности работы',
                'verbose_name_plural': 'Оценки сложности работ',
            },
        ),
        migrations.AddConstraint(
            model_name='workdifficulty',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='uniq_difficulty_per_work'),
        ),
    ]
