# Generated by Django 4.2.30 on 2026-08-10 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0036_work_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='Необязательно.', max_length=120, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, help_text='Например: «призёр регионального этапа». Необязательно.', max_length=200, verbose_name='Цель на год'),
        ),
        migrations.CreateModel(
            name='TutorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Заметка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_about_me', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_notes', to=settings.AUTH_USER_MODEL, verbose_name='Репетитор')),
            ],
            options={
                'verbose_name': 'Заметка об ученике',
                'verbose_name_plural': 'Заметки об учениках',
            },
        ),
        migrations.AddConstraint(
            model_name='tutornote',
            constraint=models.UniqueConstraint(fields=('tutor', 'student'), name='uniq_note_per_student'),
        ),
    ]
