# Generated by Django 4.2.30 on 2026-08-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0037_student_card'),
    ]

    # ⚠️ ОПЕРАЦИИ ПЕРЕСТАВЛЕНЫ ВРУЧНУЮ. Автодетектор поставил AddConstraint
    # на `custom_part` РАНЬШЕ AddField, который это поле создаёт, — ровно та
    # же ловушка, что была в миграции 0023. Сначала поля, потом ограничения.
    operations = [
        migrations.CreateModel(
            name='CustomProblemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например: а, б, в', max_length=10, verbose_name='Метка пункта')),
                ('statement', models.TextField(blank=True, verbose_name='Условие пункта')),
                ('answer', models.TextField(blank=True, verbose_name='Правильный ответ')),
                ('answer_tolerance', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Допуск')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес пункта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Пункт своей задачи',
                'verbose_name_plural': 'Пункты своих задач',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='answerdraft',
            name='uniq_answer_draft_whole',
        ),
        migrations.RemoveConstraint(
            model_name='partanswer',
            name='uniq_part_answer_whole',
        ),
        migrations.AddField(
            model_name='customproblempart',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='problems.customproblem', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='answerdraft',
            name='custom_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='problems.customproblempart', verbose_name='Пункт своей задачи'),
        ),
        migrations.AddField(
            model_name='partanswer',
            name='custom_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='problems.customproblempart', verbose_name='Пункт своей задачи'),
        ),
        migrations.AddConstraint(
            model_name='answerdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_part__isnull', False)), fields=('attempt', 'problem_item', 'custom_part'), name='uniq_answer_draft_custom'),
        ),
        migrations.AddConstraint(
            model_name='answerdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_part__isnull', True), ('part__isnull', True)), fields=('attempt', 'problem_item'), name='uniq_answer_draft_whole'),
        ),
        migrations.AddConstraint(
            model_name='partanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_part__isnull', False)), fields=('submission', 'custom_part'), name='uniq_part_answer_custom'),
        ),
        migrations.AddConstraint(
            model_name='partanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_part__isnull', True), ('part__isnull', True)), fields=('submission',), name='uniq_part_answer_whole'),
        ),
    ]
