# Generated by Django 4.2.30 on 2026-08-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0039_group_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesmosGraph',
        ),
    ]
