# Generated by Django 4.2.30 on 2026-08-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0039_group_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='hidden_pending_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Скрыта из каталога, потому что человек её ещё не смотрел', verbose_name='Скрыта до проверки человеком'),
        ),
        migrations.AddField(
            model_name='problem',
            name='human_review',
            field=models.CharField(blank=True, choices=[('', 'не смотрели'), ('approved', 'одобрено человеком'), ('defect', 'человек нашёл брак')], db_index=True, default='', help_text='Что сказал человек, посмотревший снимок страницы задачи', max_length=16, verbose_name='Человеческое ревью'),
        ),
    ]
