# Generated by Django 4.2.30 on 2026-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0040_human_review_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewverdict',
            name='category',
            field=models.CharField(choices=[('perfect', 'Идеально'), ('broken_formula', 'Сломанная формула'), ('bare_math', 'Голая математика / $'), ('merged_structure', 'Слипшийся список или структура'), ('leaked_solution', 'Утёкшее «Решение:/Ответ:»'), ('junk', 'Мусор (колонтитулы, номера страниц, обрубки)'), ('broken_table', 'Развалившаяся таблица'), ('other', 'Прочее (с комментарием)'), ('disputed', 'Спорно'), ('trash', 'Гагно'), ('fixed_wrong', 'Починил не то')], max_length=32, verbose_name='Категория'),
        ),
    ]
