# Generated by Django 4.2.30 on 2026-08-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0041_review_fixed_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewverdict',
            name='quotes',
            field=models.JSONField(blank=True, default=list, verbose_name='Цитаты'),
        ),
    ]
