# Generated by Django 5.2.17 on 2026-08-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0040_delete_desmosgraph'),
        ('problems', '0042_review_quotes'),
    ]

    operations = [
    ]
