# Generated by Django 5.2.17 on 2026-08-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0043_merge_0040_delete_desmosgraph_0042_review_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='embedding_built_at',
            field=models.DateTimeField(blank=True, help_text='NULL у записей, чей вектор посчитан ДО этой сессии — легаси, это ожидаемо, не баг.', null=True, verbose_name='Когда посчитан эмбеддинг'),
        ),
        migrations.AddField(
            model_name='problem',
            name='embedding_model_build',
            field=models.CharField(blank=True, default='', help_text='EMBEDDING_MODEL_BUILD (problems/embedding_config.py) на момент расчёта. Пусто — вектор посчитан до версионирования.', max_length=64, verbose_name='Сборка модели эмбеддинга'),
        ),
        migrations.AddField(
            model_name='problem',
            name='embedding_source_hash',
            field=models.CharField(blank=True, default='', help_text='MD5 текста, который реально закодирован (problem_to_text) на момент расчёта. Пусто — вектор посчитан до версионирования.', max_length=32, verbose_name='Хеш текста эмбеддинга'),
        ),
        migrations.AddField(
            model_name='problem',
            name='embedding_version',
            field=models.IntegerField(blank=True, help_text='EMBEDDING_FORMULA_VERSION (problems/embedding_config.py) на момент расчёта. NULL — вектор посчитан до версионирования.', null=True, verbose_name='Версия формулы эмбеддинга'),
        ),
    ]
