# Generated by Django 5.2.17 on 2026-08-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0044_embedding_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='content_format',
            field=models.CharField(choices=[('plain', 'Обычный текст'), ('markdown', 'Markdown')], default='plain', help_text='PLAIN — текущее поведение (не трогать). MARKDOWN — через math-aware рендерер, для новых источников.', max_length=20, verbose_name='Формат текста'),
        ),
    ]
