# Generated by Django 5.2.17 on 2026-08-27 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0045_problem_content_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field', models.CharField(blank=True, max_length=20, verbose_name='Поле-источник')),
                ('tikz_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хеш TikZ-блока')),
                ('tikz_source', models.TextField(verbose_name='Исходный TikZ-блок')),
                ('svg', models.TextField(verbose_name='SVG (санитизированный)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерирована')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='problems.problempart', verbose_name='Подпункт')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Сгенерированная картинка',
                'verbose_name_plural': 'Сгенерированные картинки',
                'constraints': [models.UniqueConstraint(fields=('problem', 'tikz_hash'), name='uniq_problem_figure_hash')],
            },
        ),
    ]
