# Generated by Django 5.2.17 on 2026-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0046_problem_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemfigure',
            name='content_type',
            field=models.CharField(blank=True, max_length=40, verbose_name='MIME-тип картинки'),
        ),
        migrations.AddField(
            model_name='problemfigure',
            name='image_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Байты картинки'),
        ),
        migrations.AlterField(
            model_name='problemfigure',
            name='svg',
            field=models.TextField(blank=True, verbose_name='SVG (санитизированный)'),
        ),
    ]
