# Generated by Django 5.2.17 on 2026-09-02 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0046_problem_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_site', models.CharField(choices=[('solvehub', 'SolveHub'), ('ile', 'ILE / iloveeconomics.ru')], max_length=20, verbose_name='Откуда взято сопоставление')),
                ('olympiad_slug', models.CharField(max_length=50, verbose_name='Слаг олимпиады')),
                ('olympiad_name', models.CharField(blank=True, max_length=300, verbose_name='Название олимпиады')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='Учебный год')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год тура')),
                ('stage', models.CharField(blank=True, max_length=50, verbose_name='Этап')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Класс')),
                ('variant', models.CharField(blank=True, max_length=100, verbose_name='Вариант')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер в туре')),
                ('event_id', models.CharField(max_length=200, verbose_name='ID тура в источнике')),
                ('record_id', models.CharField(max_length=300, verbose_name='ID записи в источнике')),
                ('match_method', models.CharField(choices=[('url_exact', 'Точное совпадение ссылки')], default='url_exact', max_length=30, verbose_name='Метод сопоставления')),
                ('match_score', models.FloatField(default=1.0, verbose_name='Уверенность сопоставления')),
                ('official_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка-источник сопоставления')),
                ('raw_meta', models.JSONField(blank=True, null=True, verbose_name='Прочие поля из экспорта')),
                ('reviewed_by_human', models.BooleanField(default=False, verbose_name='Проверено человеком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Найдено')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_refs', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Привязка к олимпиаде',
                'verbose_name_plural': 'Привязки к олимпиадам',
                'ordering': ['olympiad_slug', 'year', 'stage'],
                'unique_together': {('problem', 'event_id')},
            },
        ),
    ]
