# Generated by Django 5.2.17 on 2026-09-02 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0046_problem_figure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewverdict',
            name='category',
            field=models.CharField(choices=[('perfect', 'Идеально'), ('broken_formula', 'Сломанная формула'), ('bare_math', 'Голая математика / $'), ('merged_structure', 'Слипшийся список или структура'), ('leaked_solution', 'Утёкшее «Решение:/Ответ:»'), ('junk', 'Мусор (колонтитулы, номера страниц, обрубки)'), ('broken_table', 'Развалившаяся таблица'), ('other', 'Прочее (с комментарием)'), ('disputed', 'Спорно'), ('trash', 'Гагно'), ('fixed_wrong', 'Починил не то'), ('wrong_answer', 'Неверный ответ')], max_length=32, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='AnswerSecondOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='anthropic', max_length=32, verbose_name='Поставщик')),
                ('model', models.CharField(max_length=64, verbose_name='Модель')),
                ('model_answer', models.TextField(blank=True, verbose_name='Ответ модели')),
                ('bank_answer', models.TextField(blank=True, verbose_name='Ответ банка')),
                ('agrees', models.BooleanField(db_index=True, verbose_name='Сошлось')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Уверенность модели')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда')),
                ('resolved', models.BooleanField(db_index=True, default=False, verbose_name='Разобрано человеком')),
                ('resolution', models.CharField(blank=True, choices=[('', 'не разобрано'), ('bank_right', 'прав банк'), ('model_right', 'права модель, задача в брак'), ('unclear', 'вопрос сам по себе спорный')], default='', max_length=16, verbose_name='Чем кончилось')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_opinions', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Второе мнение по ответу',
                'verbose_name_plural': 'Вторые мнения по ответам',
                'indexes': [models.Index(fields=['problem', '-created_at'], name='idx_opinion_problem_time')],
            },
        ),
    ]
