# Generated by Django 5.2.17 on 2026-08-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0047_problem_figure_raster'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='reasoning_tokens',
            field=models.IntegerField(default=0, verbose_name='Токенов рассуждения'),
        ),
        migrations.AddField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('canonical', 'Канонический тег таксономии'), ('author', 'Имя составителя задачи'), ('legacy', 'Наследие импорта, не используется'), ('junk', 'Мусор: URL, обрывок комментария')], db_index=True, default='legacy', max_length=16, verbose_name='Вид тега'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_canonical',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Каноническая тема таксономии'),
        ),
    ]
