# Generated by Django 5.2.17 on 2026-09-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0047_answer_second_opinion'),
        ('problems', '0048_alter_olympiadref_match_method'),
    ]

    operations = [
    ]
