# Generated by Django 5.2.17 on 2026-09-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0048_alter_olympiadref_match_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadref',
            name='match_method',
            field=models.CharField(choices=[('url_exact', 'Точное совпадение ссылки'), ('url_www_normalized', 'Совпадение после нормализации www/схемы'), ('text_sha1', 'Точное совпадение нормализованного текста'), ('text_fuzzy_numeric', 'Высокое текстовое сходство + совпадение чисел')], default='url_exact', max_length=30, verbose_name='Метод сопоставления'),
        ),
    ]
