# Generated by Django 5.2.17 on 2026-08-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0048_aiusagelog_reasoning_tokens_tag_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title_candidate',
            field=models.CharField(blank=True, max_length=60, verbose_name='Заголовок-кандидат'),
        ),
        migrations.AddField(
            model_name='problem',
            name='title_source',
            field=models.CharField(blank=True, choices=[('model-empty', 'Модель: старый заголовок пуст/заглушка'), ('model-broken', 'Модель: старый заголовок сломан'), ('model-firstline', 'Модель: старый заголовок — эхо начала условия'), ('kept', 'Старый заголовок оставлен как есть')], max_length=20, verbose_name='Источник заголовка-кандидата'),
        ),
    ]
