# Generated by Django 5.2.17 on 2026-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0049_title_candidate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='content_status',
            field=models.CharField(choices=[('ok', 'Текст в порядке'), ('needs_fix', 'Текст требует доработки'), ('junk', 'Помечено к удалению')], db_index=True, default='ok', help_text='Пригоден ли текст к показу ученику (не оценка качества задачи и не результат ревью человеком)', max_length=16, verbose_name='Состояние текста'),
        ),
    ]
