# Generated by Django 5.2.17 on 2026-09-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0049_merge_20260902_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('novice', 'Новичок'), ('basic', 'Базовый'), ('region', 'Региональный'), ('final', 'Всеросник')], help_text='Необязательно. Нужен, чтобы подбирать задачи по силам.', max_length=16, verbose_name='Уровень подготовки'),
        ),
    ]
