# Generated by Django 5.2.17 on 2026-09-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0049_alter_olympiadref_match_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadref',
            name='is_best_in_cluster',
            field=models.BooleanField(db_index=True, default=False, help_text='Стоит у всех строк задачи-победителя кластера. При равных счетах побеждает наименьший problem_id — правило детерминировано, иначе победитель менялся бы от прогона к прогону.', verbose_name='Лучшая версия в кластере'),
        ),
        migrations.AddField(
            model_name='olympiadref',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Больше — лучше. Осмысленно только при сравнении версий ОДНОЙ задачи внутри кластера дублей; абсолютное значение ни о чём не говорит.', null=True, verbose_name='Счёт качества версии'),
        ),
    ]
