# Generated by Django 5.2.17 on 2026-09-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0049_merge_20260902_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='character',
            field=models.CharField(blank=True, choices=[('', 'не размечено'), ('qual', 'Качественная'), ('quant', 'Количественная')], db_index=True, default='', max_length=8, verbose_name='Характер задачи'),
        ),
        migrations.AddField(
            model_name='problem',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='Особенности'),
        ),
    ]
