# Generated by Django 5.2.17 on 2026-09-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0050_problem_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer_consistency',
            field=models.CharField(blank=True, choices=[('согласован', 'Ответ согласован с решением'), ('ответ_не_совпадает_с_решением', 'Ответ не совпадает с решением'), ('решение_отсутствует_проверить_нечем', 'Решения нет — проверить нечем'), ('ответ_пуст_решение_есть', 'Ответ пуст, решение есть'), ('подозрение_на_утечку_решения_в_условии', 'Подозрение на утечку решения в условие')], help_text='Из обогащения v2, вызов 2. Пусто — задача вне прогона обогащения.', max_length=64, verbose_name='Согласованность ответа (обогащение)'),
        ),
    ]
