# Generated by Django 5.2.17 on 2026-09-04 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0050_problem_character_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст решения')),
                ('solution_viewed_before', models.BooleanField(default=False, verbose_name='Решение открыли до отправки')),
                ('status', models.CharField(choices=[('checked', 'проверена'), ('needs_human', 'модель не ставит балл'), ('error', 'проверка не удалась')], default='error', max_length=16, verbose_name='Статус')),
                ('verdict', models.CharField(blank=True, choices=[('', 'нет'), ('ok', 'верно'), ('partial', 'частично верно'), ('wrong', 'неверно'), ('needs_human', 'нужен человек')], default='', max_length=16, verbose_name='Вердикт')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Балл')),
                ('max_score', models.PositiveSmallIntegerField(default=10, verbose_name='Максимум')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='Шаги')),
                ('first_error_step', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Первый ошибочный шаг')),
                ('confidence', models.CharField(blank=True, choices=[('', 'нет'), ('high', 'высокая'), ('medium', 'средняя'), ('low', 'низкая')], default='', max_length=8, verbose_name='Уверенность модели')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Итог одной строкой')),
                ('ocr_text', models.TextField(blank=True, verbose_name='Текст, распознанный с фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('files', models.ManyToManyField(blank=True, related_name='catalog_attempts', to='problems.fileasset', verbose_name='Файлы')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_attempts', to='problems.problem', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Попытка в каталоге',
                'verbose_name_plural': 'Попытки в каталоге',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'problem', 'created_at'], name='catalog_attempt_user_prob_idx')],
            },
        ),
    ]
