# Generated by Django 5.2.17 on 2026-09-04 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0051_studentgroup_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('problem', 'Проблема'), ('idea', 'Предложение')], max_length=16, verbose_name='Что это')),
                ('page_key', models.CharField(db_index=True, max_length=32, verbose_name='Экран')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='Выбранные варианты')),
                ('other_text', models.TextField(blank=True, verbose_name='Своими словами')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('screenshot', models.ImageField(blank=True, upload_to='feedback/%Y/%m/', verbose_name='Снимок экрана')),
                ('viewport', models.CharField(blank=True, max_length=32, verbose_name='Окно')),
                ('theme', models.CharField(blank=True, max_length=16, verbose_name='Тема')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Браузер')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('handled', models.BooleanField(db_index=True, default=False, verbose_name='Разобрано')),
                ('note', models.TextField(blank=True, verbose_name='Пометка для своих')),
                ('user', models.ForeignKey(blank=True, help_text='Пусто — писал гость.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='Кто написал')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
    ]
