# Generated by Django 5.2.17 on 2026-09-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0051_catalog_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='generated_by_ai',
            field=models.BooleanField(default=False, verbose_name='Сгенерирована ИИ'),
        ),
        migrations.AddField(
            model_name='hint',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Проверена человеком'),
        ),
    ]
