# Generated by Django 5.2.17 on 2026-09-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0052_feedback'),
        ('problems', '0053_hint_reviewed_backfill'),
    ]

    operations = [
    ]
