# Generated by Django 5.2.17 on 2026-09-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0051_problem_answer_consistency'),
        ('problems', '0054_merge_0052_feedback_0053_hint_reviewed_backfill'),
    ]

    operations = [
    ]
