# Generated by Django 5.2.17 on 2026-09-07 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0055_merge_20260907_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical', models.CharField(max_length=200, unique=True, verbose_name='Каноническая форма')),
                ('section', models.CharField(blank=True, max_length=200, verbose_name='Раздел словаря')),
            ],
            options={
                'verbose_name': 'Экономическое понятие',
                'verbose_name_plural': 'Экономические понятия',
                'ordering': ['canonical'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=48, unique=True, verbose_name='Ключ')),
                ('label', models.CharField(max_length=80, verbose_name='Подпись')),
                ('counted_by', models.CharField(choices=[('model', 'Модель'), ('code', 'Код')], db_index=True, max_length=8, verbose_name='Кто считает')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок показа')),
            ],
            options={
                'verbose_name': 'Особенность задачи',
                'verbose_name_plural': 'Особенности задач',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='concepts_offlist',
            field=models.JSONField(blank=True, default=list, verbose_name='Понятия вне словаря'),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty_note',
            field=models.TextField(blank=True, verbose_name='Обоснование сложности'),
        ),
        migrations.AddField(
            model_name='problem',
            name='enrichment_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда разложено'),
        ),
        migrations.AddField(
            model_name='problem',
            name='enrichment_source',
            field=models.CharField(blank=True, choices=[('run1', 'Первый прогон (слабый, ждёт допрогона)'), ('run2', 'Второй прогон (эталон)'), ('run2b', 'Допрогон вторым промптом')], db_index=True, max_length=8, verbose_name='Откуда раскладка'),
        ),
        migrations.AddField(
            model_name='problem',
            name='find',
            field=models.TextField(blank=True, verbose_name='Найти'),
        ),
        migrations.AddField(
            model_name='problem',
            name='given',
            field=models.TextField(blank=True, verbose_name='Дано'),
        ),
        migrations.AddField(
            model_name='problem',
            name='plot',
            field=models.TextField(blank=True, help_text='Заполняется только у задач с решением: без решения модель видит не механизм, а пересказ условия.', verbose_name='Сюжет'),
        ),
        migrations.AddField(
            model_name='problem',
            name='search_queries',
            field=models.JSONField(blank=True, default=list, verbose_name='Поисковые запросы'),
        ),
        migrations.AddField(
            model_name='problem',
            name='task_nature',
            field=models.CharField(blank=True, choices=[('расчётная', 'Расчётная'), ('теоретическая', 'Теоретическая'), ('качественная', 'Качественная'), ('не_задача', 'Не задача')], db_index=True, max_length=16, verbose_name='Характер задачи (обогащение)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='text_quality',
            field=models.CharField(blank=True, choices=[('чистая', 'Текст чистый'), ('мелкие_дефекты', 'Мелкие дефекты'), ('серьёзные_дефекты', 'Серьёзные дефекты'), ('не_задача', 'Не задача')], db_index=True, max_length=20, verbose_name='Качество текста (обогащение)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='text_quality_note',
            field=models.TextField(blank=True, verbose_name='Что не так с текстом'),
        ),
        migrations.AddField(
            model_name='problem',
            name='topic_confidence',
            field=models.CharField(blank=True, choices=[('высокая', 'Высокая'), ('средняя', 'Средняя'), ('низкая', 'Низкая')], db_index=True, max_length=10, verbose_name='Уверенность в теме'),
        ),
        migrations.AddField(
            model_name='problem',
            name='econ_concepts',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.econconcept', verbose_name='Экономические понятия'),
        ),
        migrations.CreateModel(
            name='ProblemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('model', 'Модель'), ('code', 'Код'), ('both', 'Модель и код')], db_index=True, max_length=8, verbose_name='Кто поставил')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_links', to='problems.feature', verbose_name='Особенность')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_links', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Особенность задачи',
                'verbose_name_plural': 'Особенности задач',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='features_rel',
            field=models.ManyToManyField(blank=True, related_name='problems', through='problems.ProblemFeature', to='problems.feature', verbose_name='Особенности (связь)'),
        ),
        migrations.AddConstraint(
            model_name='problemfeature',
            constraint=models.UniqueConstraint(fields=('problem', 'feature'), name='uniq_problem_feature'),
        ),
    ]
