# Generated by Django 5.2.17 on 2026-09-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0057_olympiadref_match_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='dup_best_rule',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Номер первого различающего признака 1-9; 9 — выбор шаткий', null=True, verbose_name='Каким признаком выиграл'),
        ),
        migrations.AddField(
            model_name='problem',
            name='dup_group',
            field=models.CharField(blank=True, db_index=True, help_text='Идентификатор группы одинаковых по тексту задач', max_length=40, verbose_name='Группа копий'),
        ),
        migrations.AddField(
            model_name='problem',
            name='dup_is_best',
            field=models.BooleanField(default=False, help_text='Лучшая версия внутри dup_group по правилам ранжирования', verbose_name='Фаворит группы копий'),
        ),
    ]
