# Generated by Django 5.2.17 on 2026-09-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0050_olympiadref_is_best_in_cluster_and_more'),
        ('problems', '0058_dup_group_marks'),
    ]

    operations = [
    ]
