# Generated by Django 5.2.17 on 2026-09-07 11:05
#
# ⚠️ ЗАЧЕМ ЭТА МИГРАЦИЯ НУЖНА ПОСЛЕ СКЛЕЙКИ 0059.
# Обе слитые ветки правили ОДНО И ТО ЖЕ поле `OlympiadRef.match_method`:
# `feat/olympiad-text-dedup` довела справочник до четырёх значений (0049),
# `main` — до восьми (0057). Сама склейка операций не несёт, и итоговое
# состояние поля в графе миграций после неё зависит от порядка обхода, то
# есть неопределено. `makemigrations --check` сразу это и показал.
# Здесь состояние поля закрепляется явно и ровно тем, что стоит в models.py:
# восемь значений. Перенумеровывать чужие миграции проект запрещает, поэтому
# расхождение снимается новой миграцией, а не правкой старых.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0059_merge_20260907_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadref',
            name='match_method',
            field=models.CharField(choices=[('url_exact', 'Точное совпадение ссылки'), ('url_www_normalized', 'Совпадение после нормализации www/схемы'), ('text_sha1', 'Точное совпадение нормализованного текста'), ('text_fuzzy_numeric', 'Высокое текстовое сходство + совпадение чисел'), ('none', 'Совпадений не найдено'), ('cosine', 'Косинусная близость векторов'), ('manual', 'Проставлено человеком'), ('propagated', 'Перенесено с копии той же задачи')], default='url_exact', max_length=30, verbose_name='Метод сопоставления'),
        ),
    ]
