# Generated by Django 5.2.17 on 2026-09-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0060_olympiadref_match_method_after_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DupMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, help_text='Связная компонента рёбер дедупа; общая у всех членов', max_length=40, verbose_name='Группа копий')),
                ('is_best', models.BooleanField(default=False, help_text='True только у фаворита уверенной группы. В группах, ушедших на ручной разбор, False у ВСЕХ.', verbose_name='Фаворит группы')),
                ('rule', models.CharField(choices=[('approved', 'Одна approved в группе — она фаворит'), ('approved_picture_review', 'У approved нет картинки, у двойника есть — смотрит человек'), ('completeness_margin', 'Фаворит по полноте с отрывом ≥ 2 баллов'), ('needs_review_tie', 'Полнота не разводит — смотрит человек'), ('needs_review_multi_approved', 'В группе больше одной approved — смотрит человек')], help_text='Общее для всей группы; говорит и причину, и уверенность', max_length=32, verbose_name='Правило выбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Размечено')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dup_mark', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Пометка группы копий',
                'verbose_name_plural': 'Пометки групп копий',
                'ordering': ['group', '-is_best', 'problem_id'],
            },
        ),
    ]
