# Generated by Django 5.2.17 on 2026-09-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0061_dupmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dupmark',
            name='rule',
            field=models.CharField(choices=[('approved', 'Одна approved в группе — она фаворит'), ('approved_picture_review', 'У approved нет картинки, у двойника есть — смотрит человек'), ('approved_answer_review', 'У approved нет ответа, у двойника есть — смотрит человек'), ('completeness_margin', 'Фаворит по полноте с отрывом ≥ 2 баллов'), ('needs_review_tie', 'Полнота не разводит — смотрит человек'), ('needs_review_multi_approved', 'В группе больше одной approved — смотрит человек')], help_text='Общее для всей группы; говорит и причину, и уверенность', max_length=32, verbose_name='Правило выбора'),
        ),
    ]
