# Generated by Django 5.2.17 on 2026-09-12 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0062_dupmark_answer_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DupHumanChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(help_text='Тот же ключ, что у DupMark.group — одно решение человека на группу; повторная разметка перезаписывает прежнее', max_length=40, unique=True, verbose_name='Группа копий')),
                ('verdict', models.CharField(choices=[('chosen', 'Фаворит выбран'), ('cannot_decide', 'Не могу решить'), ('not_duplicates', 'Это вообще не дубли')], max_length=16, verbose_name='Вердикт')),
                ('reason_tags', models.CharField(blank=True, help_text='Через запятую; список допустимых — problems/dedup.py, REASON_TAGS. Необязательны: пустое значение легитимно', max_length=200, verbose_name='Быстрые причины')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('labeled_at', models.DateTimeField(verbose_name='Размечено')),
                ('chosen_problem', models.ForeignKey(blank=True, help_text='Пусто у вердиктов «не могу решить» и «не дубли»', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dup_human_choices', to='problems.problem', verbose_name='Выбранный фаворит')),
            ],
            options={
                'verbose_name': 'Решение человека по группе копий',
                'verbose_name_plural': 'Решения человека по группам копий',
                'ordering': ['group'],
            },
        ),
    ]
