# Generated by Django 5.2.17 on 2026-09-12 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0063_dup_human_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL, verbose_name='Кто'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['kind', 'created_at'], name='problems_ai_kind_c2b8a0_idx'),
        ),
    ]
