# Generated by Django 5.2.17 on 2026-09-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0064_alter_aiusagelog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='screenshot_note',
            field=models.CharField(blank=True, max_length=16, verbose_name='Что со снимком'),
        ),
    ]
