# Generated by Django 5.2.17 on 2026-09-15 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0065_feedback_screenshot_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_question_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вопрос игры')),
                ('source', models.CharField(choices=[('catalog', 'Каталог'), ('game', 'Wecon Rush')], max_length=16, verbose_name='Откуда')),
                ('kind', models.CharField(choices=[('not_problem', 'Это вообще не задача'), ('no_question', 'Непонятно, что нужно найти'), ('figure', 'Графика или таблицы нет, либо они неправильные'), ('display', 'Плохо отображается: формулы, символы, обрывки текста'), ('other', 'Другое')], max_length=16, verbose_name='Что не так')),
                ('text', models.TextField(blank=True, verbose_name='Подробнее')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Браузер')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('handled', models.BooleanField(db_index=True, default=False, verbose_name='Разобрано')),
                ('note', models.TextField(blank=True, verbose_name='Пометка для своих')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports', to='problems.problem', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, help_text='Пусто — писал гость.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports', to=settings.AUTH_USER_MODEL, verbose_name='Кто написал')),
            ],
            options={
                'verbose_name': 'Жалоба на задачу',
                'verbose_name_plural': 'Жалобы на задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
