# Generated by Django 5.2.17 on 2026-09-15 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0066_problem_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('visitor', models.CharField(db_index=True, help_text='Cookie weco_vid: один браузер.', max_length=40, verbose_name='Посетитель')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Сессия')),
                ('page_key', models.CharField(db_index=True, max_length=32, verbose_name='Экран')),
                ('path', models.CharField(max_length=500, verbose_name='Адрес')),
                ('name', models.CharField(db_index=True, max_length=48, verbose_name='Событие')),
                ('props', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, мс')),
                ('viewport', models.CharField(blank=True, max_length=16, verbose_name='Окно')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='Браузер')),
                ('user', models.ForeignKey(blank=True, help_text='Пусто — гость.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Событие беты',
                'verbose_name_plural': 'События беты',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['name', 'ts'], name='problems_ev_name_647b02_idx'), models.Index(fields=['visitor', 'ts'], name='problems_ev_visitor_07a921_idx')],
            },
        ),
    ]
