# Generated by Django 5.2.17 on 2026-09-15 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0067_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/%Y/%m/', verbose_name='Файл')),
                ('mime', models.CharField(max_length=40, verbose_name='Тип')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('pages', models.PositiveSmallIntegerField(default=0, verbose_name='Картинок в модель')),
                ('pages_json', models.JSONField(blank=True, default=list, verbose_name='Картинки для модели')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_attachments', to='problems.problem', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Вложение чата',
                'verbose_name_plural': 'Вложения чата',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.UUIDField(blank=True, db_index=True, help_text='Генерирует страница при загрузке: вкладка — разговор.', null=True, verbose_name='Разговор')),
                ('mode', models.CharField(choices=[('free', 'Вопрос'), ('theory', 'Объясни теорию'), ('method', 'Как решать'), ('check', 'Проверь моё решение')], default='free', max_length=10, verbose_name='Режим')),
                ('user_text', models.TextField(blank=True, verbose_name='Реплика ученика')),
                ('vision_text', models.TextField(blank=True, verbose_name='Расшифровка фото')),
                ('vision_input_tokens', models.PositiveIntegerField(default=0, verbose_name='Зрение: вход')),
                ('vision_output_tokens', models.PositiveIntegerField(default=0, verbose_name='Зрение: выход')),
                ('reply', models.TextField(blank=True, verbose_name='Ответ помощника')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='Поставщик')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='Модель')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Вход')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Выход')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Стоимость, $')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='Время ответа, мс')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='problems.chatattachment', verbose_name='Вложение')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_turns', to='problems.problem', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_turns', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Реплика чата',
                'verbose_name_plural': 'Реплики чата',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='problems_ch_thread_2da892_idx')],
            },
        ),
    ]
