# Generated by Django 5.2.17 on 2026-09-18 00:28
"""Профиль беты (18.09.2026): класс списком, новые поля самоотчёта.

Класс был числом 5…11, стал кодом: `le7`, `8`…`11`, `none`. Переход тремя
шагами: столбец становится строкой с NULL, данные переводятся, NULL
заменяется пустой строкой.

Вперёд: 5, 6, 7 → `le7`; 8…11 → та же строка; NULL → ''.
Назад: `le7` → 7 (⚠️ различие 5/6/7 теряется безвозвратно — после перехода
его нет в данных); `none` и '' → NULL; 8…11 → число.
"""
from django.db import migrations, models

YOUNG = ('5', '6', '7')


def grade_to_codes(apps, schema_editor):
    UserProfile = apps.get_model('problems', 'UserProfile')
    UserProfile.objects.filter(grade__in=YOUNG).update(grade='le7')
    UserProfile.objects.filter(grade__isnull=True).update(grade='')


def grade_to_numbers(apps, schema_editor):
    UserProfile = apps.get_model('problems', 'UserProfile')
    UserProfile.objects.filter(grade='le7').update(grade='7')
    UserProfile.objects.filter(grade__in=('none', '')).update(grade=None)


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0068_chat_turn_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hours_week',
            field=models.CharField(blank=True, choices=[('lt1', 'Меньше 1'), ('1_3', '1–3'), ('3_6', '3–6'), ('gt6', 'Больше 6')], default='', max_length=8, verbose_name='Часов в неделю'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='olympiad_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Какие олимпиады писал'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prep_mode',
            field=models.JSONField(blank=True, default=list, verbose_name='Как готовлюсь'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='source_channel',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram-канал'), ('teacher', 'Преподаватель'), ('friend', 'Друг'), ('search', 'Поиск в интернете'), ('other', 'Другое')], default='', max_length=16, verbose_name='Откуда узнали'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Класс'),
        ),
        migrations.RunPython(grade_to_codes, grade_to_numbers),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('le7', '7 класс и младше'), ('8', '8 класс'), ('9', '9 класс'), ('10', '10 класс'), ('11', '11 класс'), ('none', 'Уже не школьник')], default='', max_length=8, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('novice', 'Ещё не участвовал'), ('basic', 'Школьный или муниципальный этап'), ('region', 'Региональный этап ВсОШ или отбор перечневой'), ('final', 'Заключительный этап ВсОШ или призёр перечневой')], help_text='Необязательно. Нужен, чтобы подбирать задачи по силам.', max_length=16, verbose_name='Уровень подготовки'),
        ),
    ]
