# Generated by Django 5.2.17 on 2026-09-18 00:28
"""Профиль беты (18.09.2026), часть 1 из 3: новые поля + класс временно nullable.

⚠️ Почему миграция разбита на три (18.09.2026, разбор прод-инцидента). Было
одной миграцией: AlterField(grade→nullable) → RunPython(UPDATE) →
AlterField(grade→choices) → AlterField(level) — всё в одной транзакции
(Migration.atomic=True по умолчанию). На проде это упало:

    OperationalError: cannot ALTER TABLE "problems_userprofile" because it
    has pending trigger events

Причина конкретная, не "просто не мешать данные со схемой": Django на
PostgreSQL создаёт ВСЕ foreign key как DEFERRABLE INITIALLY DEFERRED
(проверено эмпирически — это характерно для всей схемы, не только этой
таблицы). UPDATE, который реально меняет хотя бы одну строку таблицы с
такой FK-колонкой (тут — user_id), ставит в очередь отложенное событие
проверки ссылочной целостности; событие разрешается только при COMMIT.
Если внутри ТОЙ ЖЕ транзакции после UPDATE идёт ALTER TABLE этой же
таблицы — Postgres отказывает, пока очередь не опустеет. На пустой
тестовой базе UPDATE не находит строк → очередь пуста → ALTER проходит,
поэтому ночной прогон (миграции на чистую PostgreSQL) был зелёным, а на
проде с непустой `problems_userprofile` — красным. Зубастый тест:
`problems/tests/test_migration_0069_beta_profile_fields.py`.

Фикс: разбить на отдельные миграции — 0069 (только схема), 0070 (только
данные), 0071 (снова только схема) — каждая своей транзакцией. К моменту
0071 данные из 0070 уже закоммичены, очередь пуста.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0068_chat_turn_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hours_week',
            field=models.CharField(blank=True, choices=[('lt1', 'Меньше 1'), ('1_3', '1–3'), ('3_6', '3–6'), ('gt6', 'Больше 6')], default='', max_length=8, verbose_name='Часов в неделю'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='olympiad_history',
            field=models.JSONField(blank=True, default=list, verbose_name='Какие олимпиады писал'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prep_mode',
            field=models.JSONField(blank=True, default=list, verbose_name='Как готовлюсь'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='source_channel',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram-канал'), ('teacher', 'Преподаватель'), ('friend', 'Друг'), ('search', 'Поиск в интернете'), ('other', 'Другое')], default='', max_length=16, verbose_name='Откуда узнали'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Класс'),
        ),
    ]
