# Generated by Django 5.2.17 on 2026-09-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0070_search_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='kind',
            field=models.CharField(choices=[('problem', 'Проблема'), ('idea', 'Предложение'), ('pulse', 'Пульс')], max_length=16, verbose_name='Что это'),
        ),
    ]
