# Generated by Django 5.2.17 on 2026-09-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0071_feedback_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Имя файла у ученика'),
        ),
        migrations.AddField(
            model_name='chatturn',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='turns_all', to='problems.chatattachment', verbose_name='Вложения'),
        ),
    ]
