# Generated by Django 5.2.17 on 2026-09-18 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0071_beta_profile_grade_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('visitor', models.CharField(blank=True, db_index=True, help_text='Cookie weco_vid: один браузер.', max_length=64, verbose_name='Посетитель')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Сессия')),
                ('query', models.CharField(max_length=300, verbose_name='Запрос')),
                ('status', models.CharField(blank=True, max_length=16, verbose_name='Умный поиск')),
                ('ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Думали, мс')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Нашли')),
                ('degraded', models.BooleanField(default=False, verbose_name='Упрощённый режим')),
                ('top_ids', models.JSONField(blank=True, default=list, verbose_name='Первые выданные задачи')),
                ('rating', models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=4, verbose_name='Оценка')),
                ('rated_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда оценил')),
                ('rating_text', models.CharField(blank=True, max_length=300, verbose_name='Что не так')),
                ('user', models.ForeignKey(blank=True, help_text='Пусто — гость.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['visitor', 'ts'], name='problems_se_visitor_816914_idx')],
            },
        ),
    ]
