# Generated by Django 5.2.17 on 2026-09-18 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0072_chat_turn_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('opened', 'Открывал'), ('solved_self', 'Решил сам'), ('solved_hint', 'С подсказкой'), ('failed', 'Не получилось')], default='opened', max_length=16, verbose_name='Как прошло')),
                ('hints_opened', models.PositiveSmallIntegerField(default=0, verbose_name='Открыто подсказок')),
                ('solution_viewed', models.BooleanField(default=False, verbose_name='Смотрел решение')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменено')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='problems.problem', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_progress', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Прогресс по задаче',
                'verbose_name_plural': 'Прогресс по задачам',
                'constraints': [models.UniqueConstraint(fields=('user', 'problem'), name='uniq_progress_user_problem')],
            },
        ),
    ]
