# Generated by Django 5.2.17 on 2026-09-22 18:34
"""Вкладка «Аккаунт» (ТЗ владельца 22.09.2026): поле Telegram и новые подписи уровней.

⚠️ ДАННЫЕ НЕ ПЕРЕПИСЫВАЮТСЯ. `AlterField` у `level` меняет только подписи в
`choices` («Ещё не участвовал» → «Новичок»): коды в базе прежние, и столбец
остаётся тем же. Телефон эта миграция НЕ ТРОГАЕТ: поле убрано из формы, но
уже собранные номера остаются лежать (решение владельца).
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0075_problem_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('novice', 'Новичок'), ('basic', 'Начинающий'), ('region', 'Продолжающий'), ('final', 'Профи')], help_text='Необязательно. Нужен, чтобы подбирать задачи по силам.', max_length=16, verbose_name='Уровень подготовки'),
        ),
    ]
