# Generated by Django 5.2.17 on 2026-09-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0076_profile_account_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatturn',
            name='quote',
            field=models.TextField(blank=True, default='', verbose_name='Цитата'),
        ),
        migrations.AddField(
            model_name='chatturn',
            name='quote_source',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Откуда цитата'),
        ),
        migrations.AddField(
            model_name='problemprogress',
            name='hints_before_reset',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Подсказок до сброса (максимум)'),
        ),
        migrations.AddField(
            model_name='problemprogress',
            name='reset_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Решить заново: когда'),
        ),
        migrations.AddField(
            model_name='problemprogress',
            name='solution_before_reset',
            field=models.BooleanField(default=False, verbose_name='Смотрел решение до сброса'),
        ),
    ]
