# Generated by Django 5.2.17 on 2026-09-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0077_chat_quote_progress_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_kind', models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Ученик сам'), ('invited', 'Ученик по приглашению')], max_length=8, verbose_name='Вид регистрации')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='utm_campaign')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='utm_content')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='utm_term')),
                ('landing_path', models.CharField(blank=True, max_length=100, verbose_name='Посадочная страница')),
                ('referrer', models.CharField(blank=True, max_length=100, verbose_name='Откуда перешёл (Referer)')),
                ('first_seen_at', models.DateTimeField(blank=True, help_text='Пусто — метки не было.', null=True, verbose_name='Первый заход с меткой')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Зарегистрирован')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_source', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Источник регистрации',
                'verbose_name_plural': 'Источники регистраций',
                'ordering': ['-created_at'],
            },
        ),
    ]
