# Generated by Django 5.2.17 on 2026-10-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0078_signup_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadref',
            name='source_site',
            field=models.CharField(choices=[('solvehub', 'SolveHub'), ('ile', 'ILE / iloveeconomics.ru'), ('official', 'Официальный архив')], help_text='official — сверено с официальным PDF организатора, а не с агрегатором.', max_length=20, verbose_name='Откуда взято сопоставление'),
        ),
    ]
