# Generated by Django 5.2.17 on 2026-10-09 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0078_signup_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pd', 'Обработка данных и пользовательское соглашение'), ('ai', 'Помощник на основе ИИ и передача данных в Сингапур')], max_length=8, verbose_name='Вид')),
                ('version', models.CharField(max_length=16, verbose_name='Редакция документов')),
                ('given_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Принято')),
                ('source', models.CharField(choices=[('register', 'Регистрация'), ('gate', 'Экран согласия при входе'), ('chat', 'Панель помощника'), ('profile', 'Профиль')], max_length=16, verbose_name='Откуда')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('superseded_at', models.DateTimeField(blank=True, null=True, verbose_name='Заменено новой редакцией')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Согласие',
                'verbose_name_plural': 'Согласия',
                'ordering': ['-given_at', '-pk'],
                'indexes': [models.Index(fields=['user', 'kind'], name='legal_consent_user_kind')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('superseded_at__isnull', True)), fields=('user', 'kind'), name='legal_one_active_consent_per_kind')],
            },
        ),
    ]
