# Generated by Django 5.2.17 on 2026-10-09 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0079_consent_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда')),
                ('user_pk', models.PositiveBigIntegerField(verbose_name='Внутренний номер пользователя')),
                ('rows_deleted', models.PositiveIntegerField(verbose_name='Строк базы удалено')),
                ('files_deleted', models.PositiveIntegerField(verbose_name='Файлов удалено')),
            ],
            options={
                'verbose_name': 'Удаление данных',
                'verbose_name_plural': 'Журнал удалений данных',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
