# Generated by Django 5.2.17 on 2026-10-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0080_erasure_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
