# Generated by Django 5.2.17 on 2026-09-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0001_initial'),
        ('problems', '0049_merge_20260902_2058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('with_timer', models.BooleanField(default=True, verbose_name='На время')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Сдана')),
                ('is_auto_submitted', models.BooleanField(default=False, verbose_name='Сдана автоматически')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Балл')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Максимум')),
                ('pending_count', models.PositiveSmallIntegerField(default=0, verbose_name='Ждут проверки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='olympiads.olympiadvariant', verbose_name='Комплект')),
            ],
            options={
                'verbose_name': 'Попытка тренировки',
                'verbose_name_plural': 'Попытки тренировок',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_draft', models.TextField(blank=True, verbose_name='Черновик ответа')),
                ('solution_draft', models.TextField(blank=True, verbose_name='Черновик решения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сохранён')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='olympiads.trainingattempt', verbose_name='Попытка')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_training_drafts', to='problems.problempart', verbose_name='Пункт')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_training_drafts', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Черновик тренировки',
                'verbose_name_plural': 'Черновики тренировок',
            },
        ),
        migrations.CreateModel(
            name='TrainingItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Балл')),
                ('max_score', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Максимум')),
                ('is_pending', models.BooleanField(default=False, verbose_name='Ждёт проверки')),
                ('comment', models.TextField(blank=True, verbose_name='Что сказала проверка')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='olympiads.trainingattempt', verbose_name='Попытка')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_training_results', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Итог по задаче',
                'verbose_name_plural': 'Итоги по задачам',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingattempt',
            index=models.Index(fields=['variant', 'user'], name='olympiads_t_variant_97c43a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingattempt',
            index=models.Index(fields=['variant', 'session_key'], name='olympiads_t_variant_59645f_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('part__isnull', False)), fields=('attempt', 'problem', 'part'), name='uniq_training_draft_part'),
        ),
        migrations.AddConstraint(
            model_name='trainingdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('part__isnull', True)), fields=('attempt', 'problem'), name='uniq_training_draft_whole'),
        ),
        migrations.AddConstraint(
            model_name='trainingitemresult',
            constraint=models.UniqueConstraint(fields=('attempt', 'problem'), name='uniq_training_result'),
        ),
    ]
