# Generated by Django 5.2.17 on 2026-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_trainingattempt_trainingdraft_trainingitemresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadvariant',
            name='is_placeholder',
            field=models.BooleanField(default=False, verbose_name='Демонстрационные данные'),
        ),
    ]
