# Generated by Django 5.2.17 on 2026-09-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0003_olympiadvariant_is_placeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionalcoordinator',
            options={'ordering': ['sort_order', 'region_name'], 'verbose_name': 'Региональный организатор', 'verbose_name_plural': 'Региональные организаторы'},
        ),
        migrations.AddField(
            model_name='regionalcoordinator',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
