# Generated by Django 5.2.17 on 2026-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0004_alter_regionalcoordinator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadbenefit',
            name='who_gets',
            field=models.CharField(blank=True, choices=[('winners', 'Только победителям'), ('both', 'Победителям и призёрам')], max_length=20, verbose_name='Кому положено'),
        ),
    ]
