# Generated by Django 5.2.17 on 2026-09-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0005_olympiadbenefit_who_gets'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadstage',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='olympiads.factsource', verbose_name='Источник'),
        ),
    ]
