# Generated by Django 5.2.17 on 2026-09-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0006_olympiadstage_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='organizer',
            field=models.TextField(verbose_name='Организатор'),
        ),
    ]
