/* calc-data.js — данные макета «Графики»: 56 карточек моделей (42 рабочие и
   14 «Скоро») с их мини-графиками из calc2.html, скелет каждой из 42 моделей
   (что вводится, чем управляется, что показывается, что считается) и слова
   для поиска. Мини-графики перенесены из разметки окна выбора без изменений:
   primitive = «тег|атрибут=значение|…». */
(function () {
  'use strict';
  var E = (window.CalcEngine = window.CalcEngine || {});

  E.BLOCKS = ['Математика', 'КПВ и КТВ', 'Совершенная конкуренция', 'Теория фирмы',
    'Несовершенная конкуренция', 'Рынок труда', 'Международная торговля', 'Выбор потребителя',
    'Макроэкономика', 'Избранные сюжеты'];

  var RAW = [
    {"k":"m-graph","b":"Математика","n":"Построение графиков","ds":"Любое число кривых, свои точки, подписи и масштаб. Без экономики.","soon":false,"p":["path|d=M18 66 H150|s=var(--ink-soft)|sw=1.5","path|d=M84 84 V10|s=var(--ink-soft)|sw=1.5","path|d=M26 24 Q60 78 96 34 T144 22|s=var(--curve-d)|sw=2.6","path|d=M26 58 L144 30|s=var(--curve-s)|sw=2.2|da=5 4","circle|cx=106|cy=36|r=3.6|s=none|f=var(--curve-d)"]},
    {"k":"m-transform","b":"Математика","n":"Деформации графика","ds":"Сдвиги, растяжения, отражения и модули; один ползунок и обе кривые сразу.","soon":false,"p":["path|d=M18 66 H150|s=var(--ink-soft)|sw=1.5","path|d=M84 84 V10|s=var(--ink-soft)|sw=1.5","path|d=M40 14 Q84 92 128 14|s=var(--curve-ghost)|sw=2.2|da=5 4","path|d=M22 14 Q66 92 110 14|s=var(--curve-d)|sw=2.6"]},
    {"k":"m-optimum","b":"Математика","n":"Максимумы и минимумы","ds":"Экстремумы, точки перегиба, выпуклые и вогнутые участки разным цветом.","soon":false,"p":["path|d=M18 50 H150|s=var(--ink-soft)|sw=1.5","path|d=M84 84 V10|s=var(--ink-soft)|sw=1.5","path|d=M26 74 C 52 6, 68 82, 84 50 C 100 18, 116 84, 142 22|s=var(--curve-d)|sw=2.6","circle|cx=46|cy=24|r=3.6|s=none|f=var(--curve-s)","circle|cx=66|cy=70|r=3.6|s=none|f=var(--curve-mc)","circle|cx=84|cy=50|r=3.6|s=none|f=var(--curve-mr)"]},
    {"k":"m-tangent","b":"Математика","n":"Функция и её производная наглядно","ds":"Точка на кривой, треугольник Δx и Δy, график производной снизу.","soon":false,"p":["path|d=M18 66 H150|s=var(--ink-soft)|sw=1.5","path|d=M84 84 V10|s=var(--ink-soft)|sw=1.5","path|d=M26 16 Q84 96 142 16|s=var(--curve-d)|sw=2.6","path|d=M84 62 L146 34|s=var(--curve-reg)|sw=2.6","path|d=M110 48 H130 V39|s=var(--curve-reg)|sw=1.5|da=5 4","circle|cx=110|cy=48|r=3.6|s=none|f=var(--curve-d)"]},
    {"k":"m-minmax","b":"Математика","n":"Функции min и max","ds":"Нижняя или верхняя огибающая нескольких функций; излом в точке смены ветви.","soon":false,"p":["path|d=M18 70 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 70 V10|s=var(--ink-soft)|sw=1.5","path|d=M24 20 L142 66|s=var(--curve-d)|sw=2.2|da=5 4","path|d=M24 64 L142 18|s=var(--curve-s)|sw=2.2|da=5 4","path|d=M24 64 L83 42 L142 66|s=var(--curve-mc)|sw=2.6","circle|cx=83|cy=42|r=3.6|s=none|f=var(--curve-mc)"]},
    {"k":"m-constraint","b":"Математика","n":"Оптимум при ограничении","ds":"Максимум или минимум цели при заданном ограничении: касание линий уровня.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M24 20 L136 74|s=var(--curve-s)|sw=2.6","path|d=M34 66 Q56 34 96 26|s=var(--curve-d)|sw=1.5|so=.4","path|d=M44 74 Q72 44 116 36|s=var(--curve-d)|sw=2.6","circle|cx=74|cy=45|r=3.6|s=none|f=var(--ink)"]},
    {"k":"ppf","b":"КПВ и КТВ","n":"Построение КПВ","ds":"Граница производства, альтернативные издержки, выпуклость.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M26 16 Q132 22 140 74|s=var(--curve-d)|sw=2.6","circle|cx=92|cy=36|r=3.6|s=none|f=var(--curve-d)"]},
    {"k":"ppfsum","b":"КПВ и КТВ","n":"Сложение КПВ","ds":"Совместная граница с изломом: сравнительное преимущество каждой стороны.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M26 24 L92 40 L140 74|s=var(--curve-d)|sw=2.6","path|d=M26 24 L92 40|s=var(--curve-s)|sw=2.2|da=5 4"]},
    {"k":"trade","b":"КПВ и КТВ","n":"КТВ. Одна страна","ds":"Точка производства на КПВ и выигрыш от торговли при известной мировой цене.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M26 22 Q120 30 132 74|s=var(--curve-d)|sw=2.6","path|d=M22 34 L140 70|s=var(--curve-s)|sw=2.6","circle|cx=78|cy=46|r=3.6|s=none|f=var(--curve-s)"]},
    {"k":"tradeprice","b":"КПВ и КТВ","n":"КТВ. Две страны-партнёра","ds":"Мировая цена не задана, а найдена: точка внутри промежутка автарктических цен.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 20 L96 74|s=var(--curve-d)|sw=2.6","path|d=M22 46 L128 74|s=var(--curve-s)|sw=2.6","path|d=M22 16 L140 74|s=var(--curve-d)|sw=1.5|da=5 4|op=.4","path|d=M22 34 L140 74|s=var(--curve-s)|sw=1.5|da=5 4|op=.4"]},
    {"k":"sd","b":"Совершенная конкуренция","n":"Спрос и предложение","ds":"Равновесие, излишки CS и PS, общественное благосостояние.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 72 L140 20|s=var(--curve-s)|sw=2.6","circle|cx=81|cy=45|r=3.6|s=none|f=var(--curve-d)"]},
    {"k":"sdsum","b":"Совершенная конкуренция","n":"Сложение спросов и предложений","ds":"Горизонтальное сложение по количеству: рыночная кривая с изломами.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 20 L74 74|s=var(--curve-d)|sw=1.5|da=5 4|op=.4","path|d=M22 34 L96 74|s=var(--curve-d)|sw=1.5|da=5 4|op=.4","path|d=M22 20 L48 47 L144 74|s=var(--curve-d)|sw=2.6"]},
    {"k":"taxes","b":"Совершенная конкуренция","n":"Налоги и субсидии","ds":"Потоварный налог, НДС, акциз и субсидии: клин между ценами, сбор бюджета, потери DWL.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","rect|x=22|y=36|w=52|h=22|f=var(--curve-tax)|op=.16","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 72 L140 20|s=var(--curve-s)|sw=2.6","path|d=M22 58 L120 12|s=var(--curve-s)|sw=2.2|da=5 4","path|d=M22 72 L112 12|s=var(--curve-s)|sw=1.5|da=5 4|op=.5"]},
    {"k":"ceil","b":"Совершенная конкуренция","n":"Пол и потолок цены","ds":"Фиксированная цена, дефицит или избыток, объём торговли по короткой стороне.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 72 L140 20|s=var(--curve-s)|sw=2.6","path|d=M18 56 H150|s=var(--curve-reg)|sw=2.6"]},
    {"k":"quota","b":"Совершенная конкуренция","n":"Квоты","ds":"Прямое ограничение объёма: цена не определена однозначно, а лежит в коридоре.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","rect|x=18|y=30|w=46|h=26|f=var(--curve-reg)|op=.16","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 72 L140 20|s=var(--curve-s)|sw=2.6","path|d=M64 78 V12|s=var(--curve-reg)|sw=2.6"]},
    {"k":"elast","b":"Совершенная конкуренция","n":"Эластичность","ds":"Точечная |Ed| и |Es|, единичная точка, связь с выручкой.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","rect|x=18|y=12|w=52|h=66|f=var(--curve-tax)|op=.16","rect|x=70|y=12|w=66|h=66|f=var(--curve-reg)|op=.16","path|d=M22 16 L136 74|s=var(--curve-d)|sw=2.6","path|d=M18 45 H70|s=var(--ink-soft)|sw=1.5|da=5 4","path|d=M70 45 V78|s=var(--ink-soft)|sw=1.5|da=5 4","circle|cx=70|cy=45|r=3.6|s=none|f=var(--curve-d)"]},
    {"k":"ext","b":"Совершенная конкуренция","n":"Внешние эффекты","ds":"MSC или MSB против частных, потери DWL, налог или субсидия Пигу.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M63 41 L88 55 L88 27 Z|s=none|f=var(--curve-dwl)|op=.16","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 74 L140 24|s=var(--curve-s)|sw=2.6","path|d=M22 56 L140 6|s=var(--curve-reg)|sw=2.6"]},
    {"k":"firmmarket","b":"Совершенная конкуренция","n":"Рынок и фирма в СК","ds":"Два графика рядом: цена рынка и она же горизонтальный спрос для фирмы.","soon":true,"p":["path|d=M14 78 H72|s=var(--ink-soft)|sw=1.5","path|d=M14 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M18 18 L68 70|s=var(--curve-d)|sw=2.6","path|d=M18 70 L68 18|s=var(--curve-s)|sw=2.6","path|d=M90 78 H148|s=var(--ink-soft)|sw=1.5","path|d=M90 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M90 44 H148|s=var(--curve-reg)|sw=2.6","path|d=M96 34 Q116 74 142 22|s=var(--cost-atc)|sw=2.2"]},
    {"k":"prod","b":"Теория фирмы","n":"Производственная функция","ds":"TP, MP и AP от труда: точка перегиба и убывающая предельная отдача.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 74 C 56 66, 74 22, 116 18 T 146 26|s=var(--curve-d)|sw=2.6","path|d=M22 70 Q66 26 146 62|s=var(--cost-mc)|sw=2.2|da=5 4","circle|cx=74|cy=41|r=3.6|s=none|f=var(--curve-d)"]},
    {"k":"costs","b":"Теория фирмы","n":"Издержки фирмы","ds":"MC, ATC, AVC, AFC; точки закрытия и безубыточности, прибыль при цене P.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M26 40 Q60 78 96 50 T150 20|s=var(--cost-atc)|sw=2.6","path|d=M26 70 Q70 64 150 16|s=var(--cost-mc)|sw=2.6"]},
    {"k":"plants","b":"Теория фирмы","n":"Сложение заводов","ds":"Горизонтальная сумма предельных издержек, условие MC₁ = MC₂.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 74 L78 16|s=var(--curve-mc)|sw=2.2|da=5 4","path|d=M22 74 L54 16|s=var(--curve-s)|sw=2.2|da=5 4","path|d=M22 74 L142 24|s=var(--cost-mc)|sw=2.6"]},
    {"k":"isoquant","b":"Теория фирмы","n":"Изокванта и изокоста","ds":"Один выпуск разными наборами L и K, касание в точке MRTS = w / r.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 20 L128 74|s=var(--curve-reg)|sw=2.6","path|d=M28 70 Q46 38 96 30|s=var(--curve-mc)|sw=2.6","path|d=M24 78 Q44 26 110 20|s=var(--curve-mc)|sw=1.5|op=.4","circle|cx=63|cy=41|r=3.6|s=none|f=var(--ink)"]},
    {"k":"mono","b":"Несовершенная конкуренция","n":"Стандартная монополия","ds":"MR = MC, монопольная цена, потери общества против конкуренции.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L140 74|s=var(--curve-d)|sw=2.6","path|d=M22 18 L88 74|s=var(--curve-mr)|sw=2.2|da=5 4","path|d=M18 52 H150|s=var(--curve-mc)|sw=2.6"]},
    {"k":"mono-nat","b":"Несовершенная конкуренция","n":"Естественная монополия","ds":"Большие постоянные издержки, убывающая ATC, ориентиры P = MC и P = ATC.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L140 74|s=var(--curve-d)|sw=2.6","path|d=M26 16 Q56 62 146 66|s=var(--cost-atc)|sw=2.6","path|d=M18 70 H150|s=var(--curve-mc)|sw=2.2|da=5 4"]},
    {"k":"mono-d1","b":"Несовершенная конкуренция","n":"Дискриминация 1-й степени","ds":"Каждая единица по своей цене спроса: нулевой излишек покупателя, нулевые потери.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L118 52 L22 52 Z|s=none|f=var(--curve-s)|op=.16","path|d=M22 18 L140 74|s=var(--curve-d)|sw=2.6","path|d=M18 52 H150|s=var(--curve-mc)|sw=2.6"]},
    {"k":"mono-d3","b":"Несовершенная конкуренция","n":"Дискриминация 3-й степени","ds":"Два сегмента рынка, общие издержки: MR1 = MR2 = MC, цены разные.","soon":false,"p":["path|d=M14 78 H72|s=var(--ink-soft)|sw=1.5","path|d=M14 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M18 18 L68 66|s=var(--curve-d)|sw=2.6","path|d=M18 18 L43 66|s=var(--curve-mr)|sw=2.2|da=5 4","path|d=M90 78 H148|s=var(--ink-soft)|sw=1.5","path|d=M90 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M94 30 L144 70|s=var(--curve-d)|sw=2.6","path|d=M94 30 L119 70|s=var(--curve-mr)|sw=2.2|da=5 4"]},
    {"k":"monopcomp","b":"Несовершенная конкуренция","n":"Монополистическая конкуренция","ds":"Долгий период: касание спроса и ATC, нулевая экономическая прибыль.","soon":true,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 22 L128 70|s=var(--curve-d)|sw=2.6","path|d=M26 26 Q72 74 146 30|s=var(--cost-atc)|sw=2.6","circle|cx=70|cy=44|r=3.6|s=none|f=var(--ink)"]},
    {"k":"mono-kink","b":"Несовершенная конкуренция","n":"Составной спрос","ds":"Спрос из двух сегментов, излом кривой и разрыв предельной выручки.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 16 L74 44 L140 74|s=var(--curve-d)|sw=2.6","path|d=M22 16 L48 44|s=var(--curve-mr)|sw=2.2|da=5 4","path|d=M74 44 L107 74|s=var(--curve-mr)|sw=2.2|da=5 4","circle|cx=74|cy=44|r=3.6|s=none|f=var(--curve-d)"]},
    {"k":"labor","b":"Рынок труда","n":"Конкурентный рынок труда","ds":"Спрос на труд как MRPL и предложение труда: оси L и W.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 74 L140 22|s=var(--curve-s)|sw=2.6","circle|cx=81|cy=46|r=3.6|s=none|f=var(--ink)"]},
    {"k":"labor-mono","b":"Рынок труда","n":"Монопсония","ds":"Один наниматель: предельные издержки труда выше предложения, занятость ниже.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 74 L140 22|s=var(--curve-s)|sw=2.6","path|d=M22 74 L96 22|s=var(--curve-mr)|sw=2.2|da=5 4","circle|cx=63|cy=62|r=3.6|s=none|f=var(--ink)"]},
    {"k":"labor-union","b":"Рынок труда","n":"Вмешательство профсоюза","ds":"Профсоюз как монополист труда или заданный пол зарплаты; занятость ниже.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 74 L140 22|s=var(--curve-s)|sw=2.6","path|d=M18 32 H150|s=var(--curve-reg)|sw=2.6"]},
    {"k":"labor-bilat","b":"Рынок труда","n":"Двусторонняя монополия","ds":"Наниматель против профсоюза: диапазон зарплат вместо единственной точки.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","rect|x=18|y=30|w=132|h=30|f=var(--curve-reg)|op=.16","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 74 L140 22|s=var(--curve-s)|sw=2.6"]},
    {"k":"smallopen","b":"Международная торговля","n":"Малая открытая экономика","ds":"Мировая цена, импорт или экспорт, тариф и квота, потери общества.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 72 L140 20|s=var(--curve-s)|sw=2.6","path|d=M18 60 H150|s=var(--curve-reg)|sw=2.6","rect|x=52|y=57|w=56|h=6|f=var(--curve-dwl)|op=.4"]},
    {"k":"bigopen","b":"Международная торговля","n":"Большие открытые экономики","ds":"Три графика: два внутренних рынка и мировой, встреча экспорта и импорта.","soon":true,"p":["path|d=M12 78 H58|s=var(--ink-soft)|sw=1.5","path|d=M12 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M16 20 L54 66|s=var(--curve-d)|sw=2.2","path|d=M16 68 L54 24|s=var(--curve-s)|sw=2.2","path|d=M68 78 H104|s=var(--ink-soft)|sw=1.5","path|d=M68 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M70 24 L102 62|s=var(--curve-d)|sw=2.2","path|d=M70 64 L102 28|s=var(--curve-s)|sw=2.2","path|d=M116 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M116 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M118 22 L148 64|s=var(--curve-d)|sw=2.2","path|d=M118 66 L148 26|s=var(--curve-s)|sw=2.2"]},
    {"k":"monoexport","b":"Международная торговля","n":"Монополист и внешний рынок","ds":"Дома своя цена, за рубежом мировая: MR внутри = Pw = MC на общем выпуске.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 18 L100 74|s=var(--curve-d)|sw=2.6","path|d=M22 18 L61 74|s=var(--curve-mr)|sw=2.2|da=5 4","path|d=M18 48 H150|s=var(--curve-reg)|sw=2.6","path|d=M22 74 L140 20|s=var(--curve-mc)|sw=2.6"]},
    {"k":"consumer","b":"Выбор потребителя","n":"Кривые безразличия","ds":"Бюджетная линия, веер кривых безразличия, оптимум и MRS в нём.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 20 L128 74|s=var(--curve-reg)|sw=2.6","path|d=M28 70 Q46 38 96 30|s=var(--curve-d)|sw=2.6","path|d=M24 78 Q44 26 110 20|s=var(--curve-d)|sw=1.5|op=.4","circle|cx=63|cy=41|r=3.6|s=none|f=var(--ink)"]},
    {"k":"cons-demand","b":"Выбор потребителя","n":"Оптимальное потребление и спрос","ds":"Оптимумы при разных ценах и собранная по ним маршаллианская кривая спроса.","soon":true,"p":["path|d=M14 78 H72|s=var(--ink-soft)|sw=1.5","path|d=M14 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M18 20 L68 70|s=var(--curve-reg)|sw=2.2","path|d=M22 66 Q36 38 62 32|s=var(--curve-d)|sw=2.2","circle|cx=42|cy=44|r=3.6|s=none|f=var(--ink)","path|d=M90 78 H148|s=var(--ink-soft)|sw=1.5","path|d=M90 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M94 20 L144 70|s=var(--curve-d)|sw=2.6"]},
    {"k":"cons-slutsky","b":"Выбор потребителя","n":"Декомпозиция по Слуцкому","ds":"Три бюджетные линии: эффект замещения и эффект дохода по отдельности.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 24 L138 74|s=var(--curve-reg)|sw=2.2","path|d=M22 16 L82 74|s=var(--curve-ghost)|sw=2.2|da=5 4","path|d=M22 44 L62 74|s=var(--curve-reg)|sw=2.2","circle|cx=72|cy=46|r=3.6|s=none|f=var(--curve-d)","circle|cx=47|cy=42|r=3.6|s=none|f=var(--curve-s)","circle|cx=38|cy=62|r=3.6|s=none|f=var(--curve-mc)"]},
    {"k":"cons-hicks","b":"Выбор потребителя","n":"Декомпозиция по Хиксу","ds":"Компенсация до прежней полезности, а не до прежнего набора: точка на той же кривой.","soon":true,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 24 L138 74|s=var(--curve-reg)|sw=2.2","path|d=M22 44 L62 74|s=var(--curve-reg)|sw=2.2","path|d=M28 70 Q48 36 104 28|s=var(--curve-d)|sw=2.6","circle|cx=72|cy=46|r=3.6|s=none|f=var(--curve-d)","circle|cx=42|cy=52|r=3.6|s=none|f=var(--curve-s)"]},
    {"k":"cons-risk","b":"Выбор потребителя","n":"Выбор в условиях неопределённости и риск","ds":"Вогнутая полезность денег: надёжный доход против лотереи с тем же средним.","soon":true,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M24 70 Q70 24 140 18|s=var(--curve-d)|sw=2.6","path|d=M32 62 L128 22|s=var(--curve-s)|sw=2.2|da=5 4","circle|cx=32|cy=62|r=3.6|s=none|f=var(--ink)","circle|cx=128|cy=22|r=3.6|s=none|f=var(--ink)","circle|cx=80|cy=42|r=3.6|s=none|f=var(--curve-reg)"]},
    {"k":"cons-icc","b":"Выбор потребителя","n":"Кривая доход-потребление","ds":"Рост дохода при прежних ценах, линия оптимумов ICC.","soon":true,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 52 L70 74|s=var(--curve-reg)|sw=1.5|op=.4","path|d=M22 36 L104 74|s=var(--curve-reg)|sw=1.5|op=.4","path|d=M22 20 L138 74|s=var(--curve-reg)|sw=1.5|op=.4","path|d=M34 64 Q62 46 104 30|s=var(--curve-d)|sw=2.6","circle|cx=38|cy=62|r=3.6|s=none|f=var(--ink)","circle|cx=66|cy=44|r=3.6|s=none|f=var(--ink)"]},
    {"k":"cons-pcc","b":"Выбор потребителя","n":"Кривая цена-потребление","ds":"Поворот бюджетной линии при смене цены, линия оптимумов PCC.","soon":true,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 20 L62 74|s=var(--curve-reg)|sw=1.5|op=.4","path|d=M22 20 L98 74|s=var(--curve-reg)|sw=1.5|op=.4","path|d=M22 20 L140 74|s=var(--curve-reg)|sw=1.5|op=.4","path|d=M38 56 Q72 44 116 52|s=var(--curve-d)|sw=2.6","circle|cx=40|cy=55|r=3.6|s=none|f=var(--ink)","circle|cx=78|cy=45|r=3.6|s=none|f=var(--ink)"]},
    {"k":"cons-engel","b":"Выбор потребителя","n":"Кривая Энгеля","ds":"Количество блага при разном доходе: нормальное благо и товар низшей категории.","soon":true,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M24 72 Q78 60 138 18|s=var(--curve-d)|sw=2.6","circle|cx=60|cy=65|r=3.6|s=none|f=var(--ink)","circle|cx=106|cy=43|r=3.6|s=none|f=var(--ink)"]},
    {"k":"cons-marshall","b":"Выбор потребителя","n":"Связь кривых и маршаллианского спроса","ds":"Два графика друг под другом: точка PCC сверху и точка спроса снизу.","soon":true,"p":["path|d=M18 44 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 44 V8|s=var(--ink-soft)|sw=1.5","path|d=M22 12 L74 42|s=var(--curve-reg)|sw=2.2","path|d=M26 40 Q42 22 68 18|s=var(--curve-d)|sw=2.2","path|d=M18 84 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 84 V50|s=var(--ink-soft)|sw=1.5","path|d=M22 52 L140 80|s=var(--curve-d)|sw=2.6","path|d=M48 30 V78|s=var(--ink-soft)|sw=1.5|da=5 4"]},
    {"k":"adas","b":"Макроэкономика","n":"AD–AS","ds":"Совокупный спрос и предложение, потенциал LRAS, разрыв выпуска.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 20 L140 68|s=var(--curve-d)|sw=2.6","path|d=M22 70 L140 22|s=var(--curve-s)|sw=2.6","path|d=M96 78 V12|s=var(--curve-mc)|sw=2.6"]},
    {"k":"islm","b":"Макроэкономика","n":"IS–LM","ds":"Товарный и денежный рынок вместе: пара (Y, r), равновесная для обоих.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 22 L140 70|s=var(--curve-d)|sw=2.6","path|d=M22 74 L140 20|s=var(--curve-s)|sw=2.6","circle|cx=81|cy=46|r=3.6|s=none|f=var(--ink)"]},
    {"k":"phillips","b":"Макроэкономика","n":"Кривая Филлипса","ds":"Размен инфляции и безработицы в коротком периоде и его исчезновение в долгом.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M26 18 L140 66|s=var(--curve-d)|sw=2.6","path|d=M84 78 V12|s=var(--curve-mc)|sw=2.6","circle|cx=84|cy=42|r=3.6|s=none|f=var(--ink)"]},
    {"k":"money","b":"Макроэкономика","n":"Денежный рынок","ds":"Спрос на деньги, фиксированное предложение ЦБ, равновесная ставка.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 20 L140 70|s=var(--curve-d)|sw=2.6","path|d=M88 78 V12|s=var(--curve-s)|sw=2.6","circle|cx=88|cy=48|r=3.6|s=none|f=var(--ink)"]},
    {"k":"loanable","b":"Макроэкономика","n":"Рынок заёмных средств","ds":"Дефицит бюджета, рост ставки, вытеснение частных инвестиций.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 22 L120 72|s=var(--curve-d)|sw=2.6","path|d=M46 22 L144 72|s=var(--curve-reg)|sw=2.2|da=5 4","path|d=M22 72 L140 20|s=var(--curve-s)|sw=2.6"]},
    {"k":"cycle","b":"Макроэкономика","n":"Деловой цикл","ds":"Колебания выпуска вокруг тренда: подъём, пик, спад, дно и фазы между ними.","soon":true,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 66 L142 22|s=var(--curve-ghost)|sw=2.2|da=5 4","path|d=M22 66 C 46 34, 62 74, 82 44 C 102 14, 118 52, 142 22|s=var(--curve-d)|sw=2.6"]},
    {"k":"cycle-adas","b":"Макроэкономика","n":"Связь делового цикла с AD–AS","ds":"Фаза цикла сверху и соответствующее ей положение AD и AS снизу.","soon":true,"p":["path|d=M14 44 H72|s=var(--ink-soft)|sw=1.5","path|d=M14 44 V8|s=var(--ink-soft)|sw=1.5","path|d=M18 36 C 32 14, 44 44, 68 16|s=var(--curve-d)|sw=2.2","path|d=M90 78 H148|s=var(--ink-soft)|sw=1.5","path|d=M90 78 V42|s=var(--ink-soft)|sw=1.5","path|d=M94 46 L146 74|s=var(--curve-d)|sw=2.2","path|d=M94 76 L146 46|s=var(--curve-s)|sw=2.2","path|d=M40 22 L108 58|s=var(--ink-soft)|sw=1.5|da=5 4"]},
    {"k":"macrolink","b":"Макроэкономика","n":"Связка четырёх моделей","ds":"Цикл, IS–LM–BP, денежный рынок и AD–AS на одном экране: один шок во всех.","soon":true,"p":["rect|x=14|y=10|w=58|h=30|rx=4|s=var(--curve-d)|sw=2.2","rect|x=88|y=10|w=58|h=30|rx=4|s=var(--curve-s)|sw=2.2","rect|x=14|y=52|w=58|h=30|rx=4|s=var(--curve-mc)|sw=2.2","rect|x=88|y=52|w=58|h=30|rx=4|s=var(--curve-mr)|sw=2.2","path|d=M72 25 H88 M72 67 H88 M43 40 V52 M117 40 V52|s=var(--ink-soft)|sw=1.5|da=5 4"]},
    {"k":"fx","b":"Макроэкономика","n":"Валютный рынок","ds":"Плавающий и фиксированный курс; интервенции при разрыве.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 20 L140 68|s=var(--curve-d)|sw=2.6","path|d=M22 72 L140 24|s=var(--curve-s)|sw=2.6","path|d=M18 58 H150|s=var(--curve-reg)|sw=2.6"]},
    {"k":"ineq","b":"Избранные сюжеты","n":"Неравенство доходов","ds":"Кривая Лоренца, коэффициент Джини, коэффициент фондов, перераспределение.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 74 L140 14|s=var(--ink-soft)|sw=1.5|da=5 4","path|d=M22 74 Q108 70 140 14|s=var(--curve-d)|sw=2.6"]},
    {"k":"laffer","b":"Избранные сюжеты","n":"Кривая Лаффера","ds":"Поступления бюджета как функция ставки; строится прогоном самой модели налога.","soon":false,"p":["path|d=M18 78 H150|s=var(--ink-soft)|sw=1.5","path|d=M18 78 V12|s=var(--ink-soft)|sw=1.5","path|d=M22 76 Q84 6 146 76|s=var(--curve-tax)|sw=2.6","circle|cx=84|cy=41|r=3.6|s=none|f=var(--curve-tax)"]},
    {"k":"exchange","b":"Избранные сюжеты","n":"Экономика обмена","ds":"Коробка Эджворта: два участника, кривая контрактов, область взаимной выгоды.","soon":true,"p":["rect|x=20|y=14|w=120|h=62|s=var(--ink-soft)|sw=1.5","path|d=M26 68 Q52 34 88 26|s=var(--curve-d)|sw=2.2","path|d=M72 64 Q108 56 134 22|s=var(--curve-s)|sw=2.2","path|d=M20 76 Q74 58 140 14|s=var(--curve-reg)|sw=2.6","circle|cx=76|cy=49|r=3.6|s=none|f=var(--ink)"]}
  ];

  /* Разбор примитива «path|d=…|s=…» в объект для разметки. */
  function prim(str) {
    var parts = str.split('|'), o = { t: parts[0] };
    for (var i = 1; i < parts.length; i++) {
      var eq = parts[i].indexOf('=');
      o[parts[i].slice(0, eq)] = parts[i].slice(eq + 1);
    }
    var stroke = o.s || 'none', fill = o.f || 'none';
    return {
      isPath: o.t === 'path', isCircle: o.t === 'circle', isRect: o.t === 'rect',
      d: o.d || '', cx: o.cx || 0, cy: o.cy || 0, r: o.r || 0,
      x: o.x || 0, y: o.y || 0, w: o.w || 0, h: o.h || 0, rx: o.rx || 0,
      stroke: stroke, fill: fill, sw: o.sw || 0, dash: o.da || 'none',
      op: o.op || '1', so: o.so || '1'
    };
  }

  E.CARDS = RAW.map(function (c) {
    return { key: c.k, block: c.b, name: c.n, desc: c.ds, soon: c.soon, prims: c.p.map(prim) };
  });
  E.card = function (key) {
    for (var i = 0; i < E.CARDS.length; i++) if (E.CARDS[i].key === key) return E.CARDS[i];
    return null;
  };
  E.LIVE_KEYS = ['sd', 'taxes', 'ceil', 'mono', 'costs', 'm-tangent'];

  /* ── СКЕЛЕТ КАЖДОЙ ИЗ 42 МОДЕЛЕЙ ───────────────────────────────────────
     fn   — функции модели: [обозначение, имя, стартовая запись];
     ax   — оси; par — параметры-числа и выбор варианта модели;
     sl   — ползунки (сдвиги кривых, регуляторы модели);
     iv   — вмешательство (инструмент → вид → сторона → величина);
     show — что включается на графике; hd — что тянется мышью на холсте;
     cv   — холст (панели); hero — главные числа ответа; more — остальные;
     ff   — итоговая функция; note — особенности, которые нельзя потерять.
     Источник — разбор кода calc2 (84-picker.js, 52-modes.js, 88-params.js, 90-explain.js, файлы сцен). */
  var S = {};
  S['m-graph'] = { fn: [['f', 'Функция', 'x^2 - 4']], ax: 'x, y · вся плоскость', par: [], sl: ['буквы из формул'], iv: null, show: [], hd: [], cv: '1 панель', hero: ['нули', 'вершины', 'пересечения'], more: [], ff: null, note: 'Список функций открытый: новая строка появляется сама.' };
  S['m-transform'] = { fn: [['f', 'Функция', 'x^2']], ax: 'x, y · вся плоскость', par: [['', 'Что делаем с графиком', 'f(x) + a · 8 видов']], sl: ['a'], iv: null, show: [], hd: [], cv: '1 панель: исходная пунктиром и итоговая', hero: ['преобразование', 'a'], more: ['правило словами'], ff: null, note: '' };
  S['m-optimum'] = { fn: [['f', 'Функция', 'x^3 - 3x']], ax: 'x, y · вся плоскость', par: [], sl: [], iv: null, show: ['выпуклость и вогнутость', 'точки перегиба'], hd: [], cv: '1 панель', hero: ['максимум', 'минимум'], more: ['экстремумы', 'перегибы'], ff: null, note: '' };
  S['m-tangent'] = { fn: [['f', 'Функция', 'x^2']], ax: 'x, y · вся плоскость', par: [['x₀', 'Точка', '1'], ['Δx', 'Шаг секущей', '1']], sl: ['x₀', 'Δx'], iv: null, show: ['секущая через две точки'], hd: ['точка x₀ в обеих панелях'], cv: '2 панели друг под другом: f и f′', hero: ['f(x₀)', 'f′(x₀)', 'угол наклона'], more: ['наклон секущей', 'уравнение касательной'], ff: null, note: '' };
  S['m-minmax'] = { fn: [['f₁', 'Функция 1', 'x^2'], ['f₂', 'Функция 2', '4 - x']], ax: 'x, y · вся плоскость', par: [['', 'Какую функцию ищем', 'min | max'], ['', 'Сколько функций', '2'], ['Z', 'Имя результата', 'Z']], sl: [], iv: null, show: [], hd: [], cv: '1 панель: fᵢ пунктиром, Z жирно', hero: ['Z = min(…)', 'точки смены ветви'], more: [], ff: null, note: '' };
  S['m-constraint'] = { fn: [['f', 'Цель f(x, y)', 'x^0.5*y^0.5'], ['g', 'Ограничение', 'x + y = 10']], ax: 'x, y', par: [['', 'Что ищем', 'максимум | минимум']], sl: [], iv: null, show: [], hd: [], cv: '1 панель: ограничение и веер линий уровня', hero: ['x*', 'y*', 'f(x*, y*)'], more: [], ff: null, note: '' };
  S.ppf = { fn: [['КПВ', 'Граница производства', '100 - x']], ax: 'X, Y', par: [['', 'Сравнить с другой КПВ', 'КПВ 2'], ['', 'Кривая комплектов', 'единиц X / Y']], sl: [], iv: null, show: ['достижимые наборы', 'недостижимые наборы', 'кривая комплектов'], hd: ['луч комплектов'], cv: '1 панель', hero: ['X max', 'Y max'], more: ['альтернативные издержки X и Y', 'тип КПВ'], ff: null, note: 'Сейчас пересчёт по кнопке «Построить», в новом виде он живой.' };
  S.ppfsum = { fn: [['КПВ₁', 'Кривая 1', '100 - X'], ['КПВ₂', 'Кривая 2', '60 - 3X']], ax: 'X, Y', par: [['', 'Сколько кривых', '2–5'], ['', 'Имя суммы', 'КПВ']], sl: [], iv: null, show: ['кривая комплектов'], hd: ['луч комплектов'], cv: '1 панель: слагаемые пунктиром, сумма', hero: ['X max', 'Y max', 'изломы'], more: ['издержки по кривым'], ff: 'Суммарная КПВ (кусочная)', note: '' };
  S.trade = { fn: [['КПВ', 'КПВ страны', '100 - X']], ax: 'X, Y', par: [], sl: ['мировая цена Px/Py'], iv: null, show: ['кривая комплектов'], hd: ['луч комплектов'], cv: '1 панель: КПВ, КТВ, точка производства', hero: ['производство', 'пределы потребления'], more: ['мировая и внутренняя цена', 'прирост против автаркии'], ff: 'КТВ страны', note: '' };
  S.tradeprice = { fn: [['КПВ₁', 'КПВ страны 1', '100 - X'], ['КПВ₂', 'КПВ страны 2', '100 - 2X']], ax: 'X, Y', par: [], sl: ['мировая цена Pw'], iv: null, show: [], hd: [], cv: '2 панели рядом: КПВ 1 и КПВ 2', hero: ['Pw', 'экспорт'], more: ['автаркические цены', 'обмен X/Y'], ff: null, note: 'Кнопка «Сбросить к равновесной» у мировой цены.' };
  S.sd = { fn: [['D', 'Спрос', '100 - Q'], ['S', 'Предложение', 'Q']], ax: 'Q, P', par: [], sl: ['сдвиг D', 'сдвиг S'], iv: null, show: ['CS', 'PS'], hd: [], cv: '1 панель', hero: ['Q*', 'P*'], more: ['CS', 'PS', 'SW'], ff: null, note: '' };
  S.sdsum = { fn: [['D₁', 'Спрос группы 1', '100 - Q'], ['D₂', 'Спрос группы 2', '60 - Q'], ['S₁', 'Предложение 1', 'Q'], ['S₂', 'Предложение 2', 'Q + 20']], ax: 'Q, P', par: [['', 'Групп спроса / предложения', '2 / 2']], sl: ['сдвиг каждой группы'], iv: null, show: ['CS', 'PS'], hd: [], cv: '1 панель: слагаемые пунктиром, суммы жирно', hero: ['Q*', 'P*'], more: ['CS, PS по группам', 'сверка'], ff: 'Суммарные D и S', note: 'Участок «рынка здесь нет» рисуется пунктиром того же цвета.' };
  S.taxes = { fn: [['D', 'Спрос', '100 - Q'], ['S', 'Предложение', 'Q']], ax: 'Q, P', par: [], sl: [], iv: 'Налог | Субсидия → вид (потоварный · НДС · акциз) → кто платит → ставка', show: ['CS', 'PS', 'бюджет', 'DWL', 'было → стало'], hd: ['клин налога'], cv: '1 панель', hero: ['Q', 'Pb', 'Ps', 'DWL'], more: ['CS', 'PS', 'сбор', 'бремя сторон'], ff: 'S′ или D′ после налога', note: '' };
  S.ceil = { fn: [['D', 'Спрос', '100 - Q'], ['S', 'Предложение', 'Q']], ax: 'Q, P', par: [], sl: ['сдвиг D', 'сдвиг S'], iv: 'Потолок | Пол → цена', show: ['CS', 'PS', 'DWL', 'было → стало'], hd: ['линия цены'], cv: '1 панель', hero: ['объём торговли', 'дефицит / избыток', 'DWL'], more: ['Qd, Qs', 'CS, PS'], ff: null, note: '' };
  S.quota = { fn: [['D', 'Спрос', '100 - Q'], ['S', 'Предложение', 'Q']], ax: 'Q, P', par: [], sl: ['сдвиг D', 'сдвиг S'], iv: 'Квота Qк → цена внутри коридора', show: ['CS', 'PS', 'рента', 'DWL', 'было → стало'], hd: ['цена в коридоре'], cv: '1 панель: закрашенный коридор цен', hero: ['Q', 'коридор цен', 'P'], more: ['рента', 'CS, PS', 'DWL'], ff: null, note: 'Сегмент из одной кнопки «Квота» больше не нужен.' };
  S.elast = { fn: [['D', 'Спрос', '100 - Q'], ['S', 'Предложение', 'Q']], ax: 'Q, P', par: [], sl: [], iv: null, show: ['точка на предложении (Es)'], hd: ['точки на D и на S'], cv: '1 панель: зоны эластичного и неэластичного спроса', hero: ['|Ed|', '|Es|'], more: ['единичная точка', 'TR и её максимум'], ff: null, note: '' };
  S.ext = { fn: [['D', 'Спрос', '100 - Q'], ['S', 'Предложение', 'Q'], ['MSB', 'Общественная выгода', '100 - Q'], ['MSC', 'Общественные издержки', 'Q']], ax: 'Q, P', par: [], sl: ['сдвиг D', 'сдвиг S'], iv: 'Корректирующий налог или субсидия Пигу', show: ['MSB', 'MSC', 'DWL'], hd: [], cv: '1 панель', hero: ['Qрын', 'Qопт', 'DWL'], more: ['налог Пигу', 'новое равновесие'], ff: null, note: 'MSB и MSC выключены, пока их не включат галочкой.' };
  S.prod = { fn: [['Q', 'Выпуск Q = f(L)', '30L^2 - L^3']], ax: 'L; Q', par: [], sl: [], iv: null, show: ['TP', 'MP', 'AP'], hd: [], cv: '2 панели друг под другом: TP и MP/AP', hero: ['перегиб TP', 'max AP'], more: ['max TP', 'MP в точке max AP'], ff: null, note: '' };
  S.costs = { fn: [['TC', 'Суммарные издержки', 'Q^3 - 6Q^2 + 15Q + 18']], ax: 'Q, P', par: [['', 'Как задаём', 'TC | кривые MC, ATC, AVC'], ['P', 'Рыночная цена', '15']], sl: ['цена P'], iv: null, show: ['MC', 'ATC', 'AVC', 'AFC', 'TC', 'VC', 'FC', 'цена и прибыль'], hd: ['линия цены'], cv: '1 панель', hero: ['Q*', 'прибыль'], more: ['закрытие (min AVC)', 'безубыточность (min ATC)', 'FC'], ff: null, note: 'Кнопка «Стандартные издержки» возвращает стартовую TC.' };
  S.plants = { fn: [['TC₁', 'Завод 1', 'Q^2'], ['TC₂', 'Завод 2', '2Q^2']], ax: 'Q, P', par: [['', 'Показать', 'TC | MC']], sl: ['совокупный выпуск Q'], iv: null, show: [], hd: [], cv: '1 панель', hero: ['Q₁', 'Q₂', 'MC'], more: ['TC', 'сверка через ∫MC'], ff: null, note: '' };
  S.isoquant = { fn: [['Q', 'Q(L, K)', 'L^0.5*K^0.5']], ax: 'L, K', par: [['w', 'Цена труда', '1'], ['r', 'Цена капитала', '2'], ['C', 'Бюджет', '100']], sl: [], iv: null, show: ['веер изоквант'], hd: [], cv: '1 панель', hero: ['L*', 'K*', 'Q'], more: ['MRTS = w/r', 'потрачено'], ff: null, note: '' };
  S.mono = { fn: [['D', 'Спрос', '100 - Q'], ['MC', 'Предельные издержки', '20']], ax: 'Q, P', par: [], sl: ['сдвиг D', 'сдвиг MC'], iv: 'Налог | Субсидия | Потолок | Пол | Квота → величина', show: ['CS', 'PS', 'VC', 'DWL', 'было → стало'], hd: ['линии потолка и пола', 'вертикаль квоты'], cv: '1 панель: D, MR, MC', hero: ['Qm', 'Pm', 'DWL'], more: ['Qc', 'CS', 'PS', 'VC'], ff: null, note: 'Излишки считаются в первой четверти, деньги бюджета в PS не входят.' };
  S['mono-nat'] = { fn: [['D', 'Спрос', '100 - Q'], ['MC', 'Предельные издержки', '20']], ax: 'Q, P', par: [['FC', 'Постоянные издержки', '800']], sl: ['сдвиг D', 'сдвиг MC'], iv: null, show: ['прибыль монополии', 'убыток при P = MC'], hd: [], cv: '1 панель: D, MR, ATC', hero: ['Qm', 'Pm', 'прибыль'], more: ['ориентиры P = MC и P = ATC'], ff: null, note: '' };
  S['mono-d1'] = { fn: [['D', 'Спрос', '100 - Q'], ['MC', 'Предельные издержки', '20']], ax: 'Q, P', par: [], sl: ['сдвиг D', 'сдвиг MC'], iv: null, show: ['прибыль'], hd: [], cv: '1 панель', hero: ['Q', 'прибыль'], more: ['CS = 0', 'DWL = 0', 'сравнение с монополией'], ff: null, note: '' };
  S['mono-d3'] = { fn: [['D₁', 'Спрос рынка 1', '100 - Q'], ['D₂', 'Спрос рынка 2', '80 - 2Q'], ['MC', 'Общие предельные издержки', '20']], ax: 'Q, P', par: [], sl: [], iv: null, show: [], hd: [], cv: '2 панели рядом: рынок 1 и рынок 2', hero: ['q₁, P₁', 'q₂, P₂'], more: ['Σ выпуск', 'MR₁ = MR₂ = MC'], ff: null, note: '' };
  S['mono-kink'] = { fn: [['D₁', 'Спрос 1', '100 - Q'], ['D₂', 'Спрос 2', '60 - Q'], ['MC', 'Предельные издержки', '20']], ax: 'Q, P', par: [['', 'Как задаём', 'индивидуальные | кусочный']], sl: [], iv: null, show: ['CS', 'VC', 'PS'], hd: [], cv: '1 панель: ломаный D, MR с разрывом', hero: ['Q*', 'P*', 'прибыль'], more: ['CS, PS, VC', 'Qc, DWL', 'кандидаты на оптимум'], ff: null, note: '' };
  S.labor = { fn: [['D', 'Спрос на труд (MRPL)', '100 - L'], ['S', 'Предложение труда', 'L']], ax: 'L, W', par: [], sl: ['сдвиг D', 'сдвиг S'], iv: 'МРОТ → W min', show: ['излишки', 'конкурентный ориентир'], hd: ['линия МРОТ'], cv: '1 панель', hero: ['L', 'W'], more: ['безработица', 'DWL'], ff: null, note: '' };
  S['labor-mono'] = { fn: [['D', 'Спрос на труд (MRPL)', '100 - L'], ['S', 'Предложение труда', 'L']], ax: 'L, W', par: [], sl: ['сдвиг D', 'сдвиг S'], iv: 'МРОТ → W min', show: ['MCL', 'конкурентный ориентир'], hd: ['линия МРОТ'], cv: '1 панель', hero: ['Lм', 'Wм', 'DWL'], more: ['Lk, Wk'], ff: null, note: '' };
  S['labor-union'] = { fn: [['D', 'Спрос на труд (MRPL)', '100 - L'], ['S', 'Предложение труда', 'L']], ax: 'L, W', par: [['', 'Профсоюз', 'монополист | диктат зарплаты']], sl: ['сдвиг D', 'сдвиг S', 'W u'], iv: 'Зарплата профсоюза W u', show: ['MRL', 'конкурентный ориентир'], hd: ['линия зарплаты'], cv: '1 панель', hero: ['Lп', 'Wп'], more: ['безработица', 'DWL'], ff: null, note: 'Сейчас подпись тумблера расходится с кнопками, чинится попутно.' };
  S['labor-bilat'] = { fn: [['D', 'Спрос на труд (MRPL)', '100 - L'], ['S', 'Предложение труда', 'L']], ax: 'L, W', par: [], sl: ['сдвиг D', 'сдвиг S'], iv: null, show: ['диапазон исходов'], hd: [], cv: '1 панель: полоса возможных зарплат', hero: ['Wм', 'Wп'], more: ['диапазон', 'занятость'], ff: null, note: 'Ответ здесь диапазон, а не точка.' };
  S.smallopen = { fn: [['D', 'Спрос', '100 - Q'], ['S', 'Предложение', 'Q']], ax: 'Q, P', par: [['Pw', 'Мировая цена', '30']], sl: ['сдвиг D', 'сдвиг S', 'Pw'], iv: 'Без вмешательства | Тариф | Квота (ввоза или вывоза) → величина', show: ['доход бюджета / рента', 'потери общества', 'автаркия'], hd: ['линия Pw'], cv: '1 панель', hero: ['Qd', 'Qs', 'импорт / экспорт'], more: ['выигрыш от торговли', 'бюджет', 'DWL'], ff: null, note: 'Вмешательство переезжает из левой части в общую карточку.' };
  S.monoexport = { fn: [['D', 'Внутренний спрос', '100 - Q'], ['MC', 'Предельные издержки', 'Q']], ax: 'Q, P', par: [['Pw', 'Мировая цена', '50']], sl: ['Pw'], iv: null, show: [], hd: [], cv: '1 панель: D, MR, MC, Pw', hero: ['q₁', 'P₁', 'экспорт'], more: ['общий выпуск', 'MR₁ = Pw = MC'], ff: null, note: 'Сейчас Pw вводится числом в поле формулы с «Построить»; станет ползунком.' };
  S.consumer = { fn: [], ax: 'x, y', par: [['Px', 'Цена x', '1'], ['Py', 'Цена y', '2'], ['I', 'Доход', '100'], ['', 'Тип предпочтений', 'Кобб-Дуглас · 5 видов'], ['a, b', 'Степени', '0,5 и 0,5']], sl: [], iv: null, show: ['веер кривых безразличия'], hd: ['концы бюджетной линии'], cv: '1 панель', hero: ['x*', 'y*'], more: ['U', 'MRS', 'Px/Py'], ff: null, note: '' };
  S['cons-slutsky'] = { fn: [], ax: 'x, y', par: [['Px', 'Цена x', '1'], ['Py', 'Цена y', '2'], ['I', 'Доход', '100'], ['', 'Тип предпочтений', 'Кобб-Дуглас']], sl: ['новая цена Px₁'], iv: 'Новая цена Px₁', show: ['веер кривых'], hd: [], cv: '1 панель: три бюджетные линии', hero: ['A', 'B', 'C'], more: ['эффект замещения', 'эффект дохода'], ff: null, note: '' };
  S.adas = { fn: [['SRAS', 'Краткосрочное предложение', '10 + 0.5Y'], ['AD', 'Совокупный спрос', '120 - 0.6Y']], ax: 'Y, P', par: [['Y*', 'Потенциальный выпуск', '100']], sl: ['сдвиг AD', 'сдвиг SRAS'], iv: null, show: ['разрыв выпуска'], hd: [], cv: '1 панель: LRAS вертикалью', hero: ['Y', 'P'], more: ['Y*', 'разрыв'], ff: null, note: 'Сдвиги макрокривых здесь главное действие; ползунков сейчас нет вовсе.' };
  S.islm = { fn: [['IS', 'Товарный рынок', '100 - 2Y'], ['LM', 'Денежный рынок', 'Y - 20']], ax: 'Y, r', par: [], sl: ['сдвиг IS', 'сдвиг LM'], iv: null, show: [], hd: [], cv: '1 панель', hero: ['Y', 'r'], more: [], ff: null, note: '' };
  S.phillips = { fn: [], ax: 'u, π', par: [['πe', 'Ожидаемая инфляция', '4'], ['u*', 'Естественная безработица', '5'], ['β', 'Наклон', '0,5']], sl: [], iv: null, show: [], hd: [], cv: '1 панель', hero: ['π при u'], more: ['таблица u → π'], ff: null, note: '' };
  S.money = { fn: [['L', 'Спрос на деньги', '100 - 5i']], ax: 'M, i', par: [['Ms', 'Предложение денег', '60']], sl: ['Ms'], iv: null, show: [], hd: [], cv: '1 панель', hero: ['i*'], more: ['Ms'], ff: null, note: '' };
  S.loanable = { fn: [['S', 'Сбережения', 'r*10'], ['D', 'Частный спрос', '100 - 10r']], ax: 'Q, r', par: [], sl: [], iv: 'Дефицит бюджета ΔG', show: ['D общий', 'было'], hd: [], cv: '1 панель', hero: ['r', 'вытеснение'], more: ['база', 'новая r'], ff: null, note: '' };
  S.fx = { fn: [['D', 'Спрос на валюту', '100 - e'], ['S', 'Предложение валюты', 'e']], ax: 'Q, e', par: [], sl: ['курс e'], iv: 'Фиксированный курс → e', show: ['дефицит / избыток валюты'], hd: ['линия курса'], cv: '1 панель', hero: ['курс'], more: ['дефицит / избыток валюты'], ff: null, note: 'Линия курса сейчас не тянется, станет как у потолка.' };
  S.ineq = { fn: [], ax: 'N %, I %', par: [['', 'Как задаём', 'доли | доходы | формула'], ['', 'Число групп', '5 (квинтили)'], ['', 'Доли групп', '8 · 12 · 16 · 24 · 40']], sl: ['сила неравенства'], iv: 'Перераспределение: налог | трансферт → τ / T', show: ['до / после'], hd: ['узлы кривой Лоренца'], cv: 'квадрат Лоренца', hero: ['Джини', 'Робин Гуд'], more: ['коэффициент фондов', 'P90/P10'], ff: null, note: 'Квадрат остаётся квадратом при любом масштабе.' };
  S.laffer = { fn: [['D', 'Спрос', '100 - Q'], ['S', 'Предложение', 'Q']], ax: 't, T', par: [['', 'Максимальная ставка на оси', '100']], sl: [], iv: null, show: ['поступления бюджета'], hd: [], cv: '1 панель: кривая строится прогоном модели налога', hero: ['ставка максимума', 'max поступления'], more: ['объём рынка'], ff: null, note: '' };
  E.SPECS = S;

  /* ── СЛОВА ДЛЯ ПОИСКА ────────────────────────────────────────────────── */
  var KW = {
    'm-graph': 'график функция парабола построить desmos нули корни вершина пересечение',
    'm-transform': 'сдвиг растяжение отражение модуль преобразование деформация',
    'm-optimum': 'экстремум максимум минимум перегиб выпуклость вогнутость',
    'm-tangent': 'производная касательная секущая наклон угол',
    'm-minmax': 'минимум максимум огибающая min max',
    'm-constraint': 'оптимум ограничение лагранж линии уровня касание',
    ppf: 'кпв граница производственных возможностей альтернативные издержки',
    ppfsum: 'сумма кпв сложение сравнительное преимущество излом',
    trade: 'ктв торговля мировая цена одна страна',
    tradeprice: 'ктв две страны мировая цена торговля экспорт импорт',
    sd: 'спрос предложение равновесие излишки cs ps рынок',
    sdsum: 'сложение спросов рыночный спрос горизонтальное суммирование группы',
    taxes: 'налог субсидия ндс акциз клин бремя сбор бюджет dwl потоварный',
    ceil: 'потолок пол цена дефицит избыток регулирование фиксированная',
    quota: 'квота коридор цен ограничение объёма рента',
    elast: 'эластичность выручка tr единичная',
    ext: 'внешний эффект экстерналии пигу msc msb общественные издержки',
    prod: 'производственная функция tp mp ap труд перегиб отдача',
    costs: 'издержки tc mc atc avc afc прибыль безубыточность закрытие фирма',
    plants: 'заводы сложение mc два завода',
    isoquant: 'изокванта изокоста mrts труд капитал',
    mono: 'монополия mr mc монопольная цена dwl налог потолок',
    'mono-nat': 'естественная монополия atc постоянные издержки регулирование',
    'mono-d1': 'дискриминация первой степени совершенная',
    'mono-d3': 'дискриминация третьей степени два рынка сегменты',
    'mono-kink': 'составной спрос излом ломаный',
    labor: 'рынок труда зарплата мрот занятость безработица',
    'labor-mono': 'монопсония mcl наниматель зарплата',
    'labor-union': 'профсоюз зарплата монополист труда',
    'labor-bilat': 'двусторонняя монополия профсоюз наниматель',
    smallopen: 'открытая экономика мировая цена импорт экспорт тариф квота пошлина',
    monoexport: 'монополист экспорт внешний рынок мировая цена',
    consumer: 'кривые безразличия бюджетная линия полезность mrs потребитель',
    'cons-slutsky': 'слуцкий эффект замещения эффект дохода',
    adas: 'ad as совокупный спрос предложение lras разрыв выпуска',
    islm: 'is lm ставка выпуск денежный товарный',
    phillips: 'филлипс инфляция безработица',
    money: 'денежный рынок ставка процента предложение денег',
    loanable: 'заёмные средства ставка вытеснение дефицит бюджета',
    fx: 'валютный рынок курс фиксированный плавающий',
    ineq: 'неравенство лоренц джини доходы перераспределение',
    laffer: 'лаффер налог ставка поступления бюджета'
  };

  function norm(s) { return String(s || '').toLowerCase().replace(/ё/g, 'е'); }
  /* Поиск: имя важнее описания, описание важнее ключевых слов. */
  E.search = function (q) {
    var qq = norm(q).trim();
    if (!qq) return null;
    var words = qq.split(/\s+/);
    var out = [];
    E.CARDS.forEach(function (c) {
      var name = norm(c.name), desc = norm(c.desc), kw = norm(KW[c.key] || ''), blk = norm(c.block);
      var score = 0;
      for (var i = 0; i < words.length; i++) {
        var w = words[i], s = 0;
        if (name.indexOf(w) === 0) s = 10; else if (name.indexOf(' ' + w) >= 0) s = 8; else if (name.indexOf(w) >= 0) s = 6;
        else if (kw.indexOf(w) >= 0) s = 4; else if (desc.indexOf(w) >= 0) s = 3; else if (blk.indexOf(w) >= 0) s = 2;
        if (!s) { score = 0; break; }
        score += s;
      }
      if (score) out.push({ key: c.key, score: score - (c.soon ? 5 : 0) });
    });
    out.sort(function (a, b) { return b.score - a.score; });
    return out.map(function (o) { return o.key; });
  };
})();
