# Generated by Django 5.2.17 on 2026-09-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VPVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('olympiad_slug', models.CharField(default='vysshaya-proba', max_length=60, verbose_name='Слаг олимпиады')),
                ('tour', models.PositiveSmallIntegerField(default=1, verbose_name='Тур')),
                ('grade_band', models.CharField(max_length=10, verbose_name='Классы')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('source_kind', models.CharField(choices=[('demo', 'Демонстрационный'), ('author', 'Авторский'), ('past', 'Прошлых лет')], max_length=10, verbose_name='Происхождение')),
                ('source_note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('duration_seconds', models.PositiveIntegerField(default=1800, verbose_name='Длительность, с')),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Максимум баллов')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Вариант ВП',
                'verbose_name_plural': 'Варианты ВП',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('mode', models.CharField(choices=[('full', 'Весь вариант'), ('block', 'Один блок'), ('endless', 'Бесконечный')], default='full', max_length=8, verbose_name='Режим')),
                ('block', models.CharField(blank=True, max_length=10, verbose_name='Блок')),
                ('with_timer', models.BooleanField(default=True, verbose_name='На время')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начата')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Сдана')),
                ('is_auto_submitted', models.BooleanField(default=False, verbose_name='Сдана автоматически')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Балл')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Максимум')),
                ('public_code', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='Публичный код')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='vp.vpvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Попытка ВП',
                'verbose_name_plural': 'Попытки ВП',
            },
        ),
        migrations.CreateModel(
            name='VPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('block', models.CharField(choices=[('snake', 'Змейка'), ('gapfill', 'Пропуск в тексте'), ('multi', 'Несколько верных'), ('analytic', 'Аналитическое'), ('single', 'Один верный')], max_length=10, verbose_name='Блок')),
                ('kind', models.CharField(choices=[('short_text', 'Короткий ответ'), ('single', 'Один вариант'), ('multi', 'Несколько вариантов'), ('match', 'Сопоставление')], max_length=12, verbose_name='Вид')),
                ('intro', models.TextField(blank=True, verbose_name='Вводный текст блока')),
                ('statement', models.TextField(verbose_name='Условие')),
                ('prefix', models.CharField(blank=True, max_length=120, verbose_name='Напечатано до пропуска')),
                ('suffix', models.CharField(blank=True, max_length=120, verbose_name='Напечатано после пропуска')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Варианты')),
                ('correct', models.JSONField(blank=True, default=list, verbose_name='Верные')),
                ('answer', models.CharField(blank=True, max_length=200, verbose_name='Эталон короткого ответа')),
                ('accepted', models.JSONField(blank=True, default=list, verbose_name='Также засчитываем')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Баллы')),
                ('wrong_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Штраф за неверный')),
                ('penalty', models.BooleanField(default=False, verbose_name='Штраф за лишнее')),
                ('figure', models.CharField(blank=True, max_length=200, verbose_name='Рисунок')),
                ('figure_caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись к рисунку')),
                ('figure_source', models.CharField(blank=True, max_length=200, verbose_name='Источник рисунка')),
                ('table_html', models.TextField(blank=True, verbose_name='Таблица (HTML)')),
                ('solution', models.TextField(blank=True, verbose_name='Решение')),
                ('chain_first', models.CharField(blank=True, db_index=True, max_length=1, verbose_name='Первая буква')),
                ('chain_second', models.CharField(blank=True, db_index=True, max_length=1, verbose_name='Вторая буква')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vp.vpvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Задание ВП',
                'verbose_name_plural': 'Задания ВП',
                'ordering': ['number'],
                'unique_together': {('variant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VPAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='Что ввёл или выбрал')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Балл')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Максимум')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vp.vpattempt', verbose_name='Попытка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vp.vpitem', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Ответ ВП',
                'verbose_name_plural': 'Ответы ВП',
                'unique_together': {('attempt', 'item')},
            },
        ),
    ]
