# Generated by Django 5.2.17 on 2026-09-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpvariant',
            name='source_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Подпись источника'),
        ),
        migrations.AddField(
            model_name='vpvariant',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на источник'),
        ),
    ]
