# Generated by Django 5.2.17 on 2026-09-22 17:39
"""Флаг зачётной попытки (решение владельца 22.09.2026) и разметка уже сыгранного.

Правило: зачётная — ПЕРВАЯ попытка человека по варианту, начатая с таймером.
Новые попытки размечает `views.start`; здесь размечается то, что уже лежит в базе,
иначе таблица лучших попыток начала бы историю с пустого места.
"""
from django.db import migrations, models


def mark_first_timed(apps, schema_editor):
    """Каждой паре (пользователь, вариант) — самая ранняя попытка с таймером."""
    VPAttempt = apps.get_model('vp', 'VPAttempt')
    seen = set()
    first = []
    rows = (VPAttempt.objects
            .filter(with_timer=True, user__isnull=False)
            .order_by('started_at', 'id')
            .values_list('pk', 'user_id', 'variant_id'))
    for pk, user_id, variant_id in rows:
        key = (user_id, variant_id)
        if key not in seen:
            seen.add(key)
            first.append(pk)
    VPAttempt.objects.filter(pk__in=first).update(is_ranked=True)


class Migration(migrations.Migration):

    dependencies = [
        ('vp', '0002_vpvariant_source_label_vpvariant_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpattempt',
            name='is_ranked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Зачётная'),
        ),
        # Обратно ничего делать не надо: поле уедет вместе с разметкой.
        migrations.RunPython(mark_first_timed, migrations.RunPython.noop),
    ]
