"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv_if_present(path):
    """Локальный `runserver` подхватывает `.env` из корня проекта; прод
    по-прежнему получает переменные из docker compose (там `.env` этого
    файла просто нет — секреты приходят через `environment`/`env_file`
    самого compose). Уже заданная переменная сильнее файла: то, что явно
    выставлено в оболочке, `.env` молча не перезаписывает.
    """
    if not path.exists():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        name, _, value = line.partition('=')
        name, value = name.strip(), value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in '"\'':
            value = value[1:-1]
        os.environ.setdefault(name, value)


_load_dotenv_if_present(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(*7+awaj76gz18jtv9(q1ejr)g05$06n5s_kpq+$vgn3t-ms$0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Наше приложение с задачами:
    'problems',
    # Этап А — Публичный каталог задач:
    'catalog',
    # Этап В1 — Кабинет ученика:
    'student',
    # Этап В2–В4 — Панель учителя:
    'teacher',
    # Этап Е — Заглушка календаря:
    'calendar_stub',
    # Этап Е — Собственный графический движок (calc2, D3 + Math.js):
    'calc2',
    # Игровая поверхность Econ Rush (публичная игра на скорость):
    'game',
    # Справочник олимпиад по экономике: даты, льготы, комплекты заданий.
    'olympiads',
    # ⚠️ `channels` СТОИТ ПОСЛЕДНИМ, И ЭТО ВАЖНО. Оно подменяет команду
    # `runserver` своей, ASGI-версией. Стоя выше `django.contrib.staticfiles`,
    # оно ломало бы отдачу статики в разработке; ниже — обе команды
    # уживаются. WebSocket нужен дуэли в реальном времени (ADR 0062).
    'channels',
]

# Используем свою модель пользователя (с ролью teacher / student).
AUTH_USER_MODEL = 'problems.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Permissions-Policy и CSP в режиме отчёта — своими настройками Django
    # их не задаёт. Подробности и обоснование — в config/security_headers.py.
    'config.security_headers.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ищем глобальные шаблоны в папке templates/ в корне проекта.
        # Это нужно чтобы переопределить admin/base_site.html (ссылка на калькулятор).
        'DIRS': [BASE_DIR / 'templates'],
        # Django 4.1+ кэширует шаблоны в памяти процесса ДАЖЕ при DEBUG=True.
        # Долго работающий runserver (особенно с --noreload) продолжает отдавать
        # СТАРЫЕ шаблоны после правок — жёсткое обновление в браузере не помогает.
        # Поэтому при DEBUG загружаем шаблоны с диска на каждый запрос.
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.site_meta',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ] if DEBUG else [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
# ⚠️ HTTP ОСТАЁТСЯ ЗА GUNICORN. ASGI поднимается ОТДЕЛЬНЫМ процессом
# (daphne) и обслуживает только `/ws/`: менять боевой веб-сервер ради одной
# долгоживущей ручки незачем, а второй процесс с тем же образом дешевле и
# откатывается отдельно. Подробности — docs/SERVER.md.
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # ⚠️ Ожидание блокировки. SQLite пускает ОДНУ запись за раз, а
        # контрольная шлёт автосохранения по ходу набора — два запроса
        # запросто оказываются в полёте вместе. По умолчанию второй падает
        # мгновенно с «database is locked», и ученик получает ошибку на
        # сохранении своей работы. Двадцать секунд ожидания снимают это
        # на локальной разработке; на проде PostgreSQL, там такого нет.
        'OPTIONS': {'timeout': 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # ⚠️ 10, а не восемь по умолчанию. Восьмизначный пароль современная
        # видеокарта перебирает быстрее, чем человек его придумывает; десять
        # — уже заметная разница, а неудобство для человека почти то же.
        # Проверяется формами Django (смена пароля); `create_user` в коде и
        # в тестах валидаторы не вызывает, поэтому фикстуры не ломаются.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# ⚠️ БЕЗ ЭТОЙ СТРОКИ ПАПКА `static/` В КОРНЕ НЕ ОТДАЁТСЯ ВООБЩЕ. Django сам
# находит только `<приложение>/static/`; корневую папку проекта он ищет
# ровно здесь. До 31.08.2026 корневой `static/` не было — вся статика жила
# по приложениям, — и вопрос не вставал. Шрифты и логотип принадлежат не
# приложению, а всему сайту, поэтому лежат в корне; без STATICFILES_DIRS
# ссылки на них отдавали бы 404, а `collectstatic` в сборке образа их бы
# не увидел.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Загруженные файлы (картинки, PDF, графики) будут лежать в папке media/.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Путь к xelatex для генерации PDF из подборок (Этап Б2)
XELATEX_PATH = '/Library/TeX/texbin/xelatex'

# На продакшене sentence-transformers не грузим (переопределяется в settings_production.py)
LOAD_EMBEDDINGS_MODEL = True

# ─── Семантический (смысловой) поиск ─────────────────────────────────────
#
# ⚠️ ЭТО ПРЕДОХРАНИТЕЛЬ ПРОТИВ МИНЫ №1, А НЕ НАСТРОЙКА УДОБСТВА.
# Модель эмбеддингов весит 2,12 ГБ и грузится в память КАЖДОГО рабочего
# процесса: на четырёх воркерах это 8,5 ГБ при 8 ГБ памяти сервера. Первый
# же запрос к смысловому поиску убил бы сервер. Пока модель не вынесена
# в отдельный процесс (мина №1), на боевом сервере поиск выключается.
#
# ⚠️ ПО УМОЛЧАНИЮ ВКЛЮЧЁН. Умолчание держит локальную разработку и весь
# существующий набор тестов в прежнем поведении: выключить — это осознанное
# действие через окружение, а не то, что случается само.
#
# Выключенный флаг означает ДЕГРАДАЦИЮ, А НЕ ОТКАЗ (правило 6.13
# docs/EMBEDDINGS.md): страница поиска отвечает 200, ищет по словам и честно
# говорит об этом человеку. Ни пятисотки, ни вечного ожидания.
#
# ⚠️ Флаг обязан проверяться ДО импорта sentence_transformers, а не после.
# Проверка после импорта бесполезна: 2,12 ГБ уже в памяти. Это стережёт
# тест, который смотрит на sys.modules.
SEMANTIC_SEARCH_ENABLED = (
    os.environ.get('SEMANTIC_SEARCH_ENABLED', '1').strip().lower()
    not in ('0', 'false', 'no', 'off', '')
)

# ─── Сервис кодирования запросов (С4) ────────────────────────────────────
#
# Адрес соседнего контейнера во внутренней сети Docker. Наружу этот порт
# не публикуется (в compose у сервиса нет секции ports) — снаружи его
# достать нельзя, и это проверяется вручную по docs/SERVER.md.
#
# ⚠️ ПУСТОЕ ЗНАЧЕНИЕ = «СЕРВИСА НЕТ», А НЕ ОШИБКА. Локальная разработка и
# прогон тестов идут без поднятого сервиса, и поиск обязан деградировать
# до поиска по словам, а не падать. Умолчание указывает на имя сервиса в
# compose, потому что именно там он и живёт.
SEARCH_SERVICE_URL = os.environ.get(
    'SEARCH_SERVICE_URL', 'http://search:8001').strip()

# ⚠️ ТАЙМАУТ КОРОТКИЙ НАМЕРЕННО. Он стоит на пути ЖИВОГО поискового
# запроса: пока он тикает, человек смотрит на крутилку. Лучше через пять
# секунд честно отдать поиск по словам, чем через минуту — то же самое.
# Первый запрос после старта сервиса дольше (модель грузится с диска), и
# он законно упадёт в деградацию — это разовая цена, а не поломка.
SEARCH_SERVICE_TIMEOUT = float(
    os.environ.get('SEARCH_SERVICE_TIMEOUT', '5').strip() or 5)

# ─── Работа с моделью (problems/ai) ──────────────────────────────────────
#
# Поставщик меняется ТОЛЬКО этой настройкой — 'anthropic', 'openai', 'fake'.
# Ключи живут в окружении (ANTHROPIC_API_KEY / OPENAI_API_KEY) и в
# репозиторий не попадают никогда.

# Цена за миллион токенов: (вход, кэш, выход). Кортеж из двух чисел
# (вход, выход) тоже понимается — цена кэша тогда выводится из входа.
# ⚠️ Числа — оценка для сметы, а не счёт поставщика. Сверить с реальным
# списанием на пилоте: по ним считается бюджет всего прогона обогащения.
AI_PRICES = {
    'gpt-5.6-terra': (2.00, 0.20, 12.00),
    'gpt-5.6-luna':  (0.20, 0.02, 1.20),
    'claude-haiku-4-5': (1.0, 0.1, 5.0),
}

# Уровень рассуждения у моделей, которые это умеют (OpenAI).
# none / low / medium / high / xhigh / max. По умолчанию выключено:
# рассуждение тарифицируется как выход, и на прогоне в 41 307 задач
# reasoning=low добавляет к смете +$74.
AI_REASONING_EFFORT = os.environ.get('AI_REASONING_EFFORT', 'none').strip()

# ─── Порог близости смыслового поиска ────────────────────────────────────
#
# Ниже этого косинуса совпадение не показываем вовсе. Без порога поиск
# всегда возвращает двадцать «самых похожих» — даже когда похожего нет, и
# на «как сварить борщ» человек получает двадцать задач про издержки.
#
# ⚠️ ЭТО НАСТРОЙКА, А НЕ ЧИСЛО В КОДЕ, И ЕЁ ПРИДЁТСЯ КАЛИБРОВАТЬ. После
# прогона обогащения отпечатки задач станут другими, и порог поедет;
# место для калибровки — Dataset B.
#
# Стартовое значение 0,55 было подобрано замером на живых запросах 01.09.2026
# под формулу v1 (корпус 14 458 видимых задач, BGE-M3):
#     бессмысленные запросы  «как сварить борщ» 0,493 · «квантовая
#                            хромодинамика» 0,423 — оба ниже порога целиком;
#     осмысленные            «монополия» 0,630 · «налог» 0,611 ·
#                            «эластичность спроса по цене» 0,778.
# Запас до ближайшего мусора — 0,057.
#
# ⚠️ Снижено до 0,40 при переходе на v2_meta_first (09.09.2026) — развёртка
# по восьми порогам на 119 запросах (наборы C58+C65) показала, что от 0,30
# до 0,55 recall@5/recall@10/nDCG@10 совпадают до четвёртого знака: порог в
# этом диапазоне НЕ влияет на ранжирование топ-10 вовсе, только на то,
# попадёт ли правильный ответ в выдачу целиком. При 0,55 отсекалось 43 из
# 119 правильных ответов (36%) без единого выигрыша в качестве; при 0,40 —
# только 6. Таблица — reports/formula_v2/search_threshold_sweep.json,
# решение — Notion «Решения». 0,30 не взяли: порог обязан оставаться хоть
# какой-то защитой от бессмысленного запроса. ⚠️ Замер «мусор vs осмысленное»
# выше — калибровка под v1, под v2_meta_first (косинусы систематически
# выше) не переснята; если появится сигнал, что 0,40 пропускает явный
# бессмысленный запрос — перезамерить.
#
# ⚠️ БЛИЗОСТЬ BGE-M3 НЕ КАЛИБРОВАНА ПО ДЛИНЕ ЗАПРОСА, И ЭТО ВИДНО ЗАМЕРОМ.
# Одно слово «монополия» даёт максимум 0,630, а абзац с описанием той же
# задачи — 0,752. Относительный порог (доля от лучшего совпадения)
# напрашивается, но это смена поведения поиска — решение владельца, а не
# побочная правка.
SEMANTIC_SEARCH_MIN_SCORE = float(
    os.environ.get('SEMANTIC_SEARCH_MIN_SCORE', '0.40').strip() or 0.40)

# ─── Переранжирование умного поиска моделью (catalog/rerank.py) ─────────
#
# За флагом, только для сотрудников (`request.user.is_staff`), только
# локально — Notion «Решения» 11.09.2026: переранжирование пула кандидатов
# GLM-5.3-Flash подняло nDCG@10 с 0,77 до 0,95 на офлайн-замере 10.09.2026
# (reports/llm_search_eval/). Умолчание — ВЫКЛЮЧЕНО: это не то же
# предохранение, что у семантического поиска (там мина в памяти), здесь
# просто платная функция, которая не должна включаться сама.
SMART_SEARCH_RERANK = (
    os.environ.get('SMART_SEARCH_RERANK', '0').strip().lower()
    in ('1', 'true', 'yes', 'on')
)
SMART_SEARCH_RERANK_MODEL = os.environ.get(
    'SMART_SEARCH_RERANK_MODEL', 'glm-5.3-flash').strip()
# Глубина каждой ноги пула (дense/bm25 топ-N) и потолок пула ПОСЛЕ дедупа.
SMART_SEARCH_RERANK_LEG_DEPTH = int(
    os.environ.get('SMART_SEARCH_RERANK_LEG_DEPTH', '50').strip() or 50)
SMART_SEARCH_RERANK_POOL_CAP = int(
    os.environ.get('SMART_SEARCH_RERANK_POOL_CAP', '150').strip() or 150)
# Размер пачки кандидатов на один вызов модели — тот же, что в замере
# 10.09.2026 (reports/llm_search_eval/reranking.py:BATCH).
SMART_SEARCH_RERANK_BATCH_SIZE = int(
    os.environ.get('SMART_SEARCH_RERANK_BATCH_SIZE', '50').strip() or 50)
# Общий бюджет времени на переранжирование одного запроса. Превышение —
# деградация до базового порядка, а не ожидание сверх этого.
SMART_SEARCH_RERANK_TIMEOUT = float(
    os.environ.get('SMART_SEARCH_RERANK_TIMEOUT', '15').strip() or 15)
# Какие ноги пула включены: 'dense', 'bm25' через запятую.
SMART_SEARCH_RERANK_LEGS = frozenset(
    leg.strip() for leg in
    os.environ.get('SMART_SEARCH_RERANK_LEGS', 'dense,bm25').split(',')
    if leg.strip())

# Этап В1 — Кабинет ученика: URL для входа и редирект по умолчанию.
LOGIN_URL = '/login/'
# Метка версии в правом углу шапки. Поднимает владелец руками: числа
# считает человек, а не сборка — на бете важно, что версию назвали, а не то,
# что она вычислилась.
SITE_VERSION = 'beta 0.0'

# ─── Где мы находимся: бой или площадка разработчиков ────────────────────────
#
# ⚠️ ЗНАЧЕНИЕ ПО УМОЛЧАНИЮ — `prod`, И ЭТО НЕ ПЕРЕСТРАХОВКА. Площадка
# `dev.weconomics.ai` работает на ТЕХ ЖЕ боевых настройках (в этом весь её
# смысл: 06.09.2026 два бага всплыли только на бою, потому что до него код
# нигде не жил в боевых условиях). Отличить её от боя может ТОЛЬКО эта
# переменная. Ошибись мы значением по умолчанию в другую сторону — бой рисовал
# бы посетителям плашку «рабочая версия, не бой».
#
# `SITE_BUILD` — короткий хеш коммита, вшитый в образ аргументом сборки
# (Dockerfile, ARG GIT_SHA). Режем до семи знаков ЗДЕСЬ, а не в шаблоне:
# подрезка в разметке повторялась бы в каждом месте, где хеш понадобится.
# На бою образ собирается без --build-arg, приезжает `unknown`, но плашку
# рисует не хеш, а SITE_ENV — так что на бою это значение никуда не выводится.
SITE_ENV = os.environ.get('SITE_ENV', 'prod').strip()
SITE_BUILD = os.environ.get('GIT_SHA', '').strip()[:7]

# Пароль двух тестовых аккаунтов площадки (`dev-teacher`, `dev-student`).
# Задаётся ТОЛЬКО в `/srv/weconomics/dev/.env` на сервере и читается
# командой `dev_scrub`. Пусто везде, кроме площадки: команда с пустым
# значением отказывается работать, а не заводит аккаунт без пароля.
DEV_ACCOUNTS_PASSWORD = os.environ.get('DEV_ACCOUNTS_PASSWORD', '').strip()

LOGIN_REDIRECT_URL = '/student/'  # переопределяется в RoleBasedLoginView
# ⚠️ ПОСЛЕ ВЫХОДА — НА ГЛАВНУЮ, А НЕ НА ФОРМУ ВХОДА (04.09.2026). Человек
# нажал «Выйти» — значит, он закончил, а не собирается войти снова. Главная
# открыта гостям и показывает, куда пойти дальше.
LOGOUT_REDIRECT_URL = '/'

# Econ Rush: сгенерированные вопросы (game/generators/) участвуют в выдаче.
# На проде выключено в settings_production.py, пока преподаватель не проверил
# превью и не принял решение о выкатке.
GAME_GENERATED_ENABLED = True


# ─── Кэш и сессии: Redis ─────────────────────────────────────────────────
#
# ⚠️ ЗАЧЕМ ЭТО ПОЯВИЛОСЬ. До 2026-08-21 здесь стоял один `LocMemCache` —
# память ОДНОГО процесса. Пока сайт жил в один процесс, это работало.
# На боевом сервере воркеров девять, и тот же словарь означал бы девять
# независимых кэшей: попадание примерно один раз из девяти, счётчик
# неудачных входов свой у каждого воркера (то есть попыток до запрета
# в девять раз больше), а сброс кэша доходил бы до одного воркера из девяти.
# Это «мина №2» из разбора боевого сервера.
#
# ⚠️ РАСКЛАДКА БАЗ REDIS — СОГЛАШЕНИЕ ПРОЕКТА, МЕНЯТЬ ТОЛЬКО ОСОЗНАННО:
#     БД 0  — кэш приложения (алиас `default`)
#     БД 1  — сессии (алиас `sessions`)
#     БД 2  — брокер Celery (зарезервировано, сейчас не используется)
#     БД 3  — channel layer для WebSocket (зарезервировано)
#     БД 14 — сессии во время прогона тестов
#     БД 15 — кэш во время прогона тестов
#
# ⚠️ ПОЧЕМУ КЭШ И СЕССИИ В РАЗНЫХ БАЗАХ. `cache.clear()` у Redis-бэкенда
# Django — это FLUSHDB: он вычищает базу Redis ЦЕЛИКОМ, а не только ключи
# своего алиаса. `cache.clear()` вызывается в 18 местах набора тестов и
# может понадобиться на сервере. Лежи сессии в той же базе — любой сброс
# кэша разлогинивал бы всех до одного. Разные базы + разные алиасы —
# единственное, что делает это невозможным по устройству, а не по договорённости.
#
# ⚠️ ПОЧЕМУ ТЕСТЫ УВОДЯТСЯ НА 15 и 14. Тесты зовут `cache.clear()`. Если
# разработчик держит в `REDIS_URL` адрес рабочего Redis, прогон вычистил бы
# его рабочий кэш. Отдельные номера баз делают это безвредным.
import os
import sys

# redis://[:пароль@]хост:порт — БЕЗ номера базы, его дописывает `_redis_cache`.
# ⚠️ Пароль внутри URL обязан быть percent-encoded: символы @ : / # ? ломают
# разбор адреса. `deploy/env.example` велит генерировать пароли только из
# латиницы и цифр — тогда кодировать нечего. Разбор проверяется ниже.
REDIS_URL = os.environ.get('REDIS_URL', '').strip()

# Прогон тестов узнаётся по argv, а не по переменной окружения: переменную
# забывают выставить ровно тогда, когда это важнее всего.
_TESTING = 'test' in sys.argv


def _redis_cache(db_index, prefix):
    """Один алиас кэша в отдельной базе Redis."""
    return {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'{REDIS_URL}/{db_index}',
        'KEY_PREFIX': prefix,
        'TIMEOUT': 300,
    }


if REDIS_URL:
    # Адрес разбирается ЗДЕСЬ, а не при первом обращении к кэшу: сломанный
    # URL должен валить старт с внятным текстом, а не отдавать пятисотку
    # первому посетителю.
    from urllib.parse import urlsplit as _urlsplit

    _parts = _urlsplit(REDIS_URL)
    if _parts.scheme not in ('redis', 'rediss', 'unix') or not _parts.netloc:
        raise ValueError(
            'REDIS_URL не разбирается как адрес Redis. Ожидается '
            'redis://хост:порт или redis://:пароль@хост:порт. Если в пароле '
            'есть @ : / # или ?, его надо percent-encode (urllib.parse.quote).'
        )
    del _parts, _urlsplit

# ⚠️ ПАРАЛЛЕЛЬНЫЙ ШАГ ПРОГОНА УВОДИТ КЭШ В ПАМЯТЬ ПРОЦЕССА, И ЭТО ГЛАВНОЕ
# МЕСТО ВСЕЙ ЗАТЕИ С `--parallel`.
#
# Django при `--parallel` даёт каждому воркеру СВОЮ тестовую базу. А Redis
# остаётся один на всех: восемь воркеров писали бы в одну базу 15, и первый
# же `cache.clear()` (их 18 в наборе) обнулял бы кэш остальным семи посреди
# их работы. Симптом был бы худшим из возможных — тесты падают случайно и
# не воспроизводятся поодиночке.
#
# ⚠️ РАЗДЕЛИТЬ ПРЕФИКСОМ КЛЮЧЕЙ НЕЛЬЗЯ. `cache.clear()` у Redis-бэкенда
# Django — это `FLUSHDB`: он чистит базу ЦЕЛИКОМ и `KEY_PREFIX` не смотрит.
# Префикс развёл бы ключи, но не спас бы от сброса.
#
# ⚠️ ОТДЕЛЬНОЙ БАЗЫ REDIS НА ВОРКЕРА ТОЖЕ НЕ ХВАТАЕТ. Баз всего 16; 0–1 под
# боевые, 2–3 зарезервированы. На машине владельца 8 ядер, то есть
# `--parallel auto` даёт 8 воркеров и потребовал бы 16 баз только под тесты.
# Схема, которая ломается от покупки нового ноутбука, — не схема.
#
# Поэтому: на параллельном шаге кэш у каждого воркера свой, в его памяти.
# Изоляция получается по устройству процесса, а не по договорённости.
# Тесты, которым нужен НАСТОЯЩИЙ Redis, помечены `@tag('serial')` и идут
# вторым шагом, где Redis снова настоящий. Подробности — docs/TESTING.md.
_LOCAL_TEST_CACHE = os.environ.get('QLS_TEST_LOCAL_CACHE', '') == '1'

# Два РАЗНЫХ `LOCATION` обязательны: одинаковое имя у LocMemCache — это один
# и тот же склад под двумя вывесками, и тогда `cache.clear()` снова уносил бы
# сессии, только уже локально.
_LOCMEM_CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qls-default',
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qls-sessions',
    },
    # Векторы поисковых запросов (С4). Своё место по той же причине, что и
    # у сессий: они дорого достаются и не должны исчезать от сброса кэша.
    'search': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qls-search',
    },
}

if REDIS_URL and not (_TESTING and _LOCAL_TEST_CACHE):
    # ⚠️ У ПОИСКА СВОЯ БАЗА (7), И ЭТО НЕ ПЕДАНТИЗМ. Вектор запроса считает
    # модель — это самая дорогая единица данных в проекте. В общей базе с
    # обычным кэшем любой штатный `cache.clear()` (а он же FLUSHDB) уносил
    # бы их вместе с мелочью, и следующая волна запросов заново будила бы
    # модель. Ровно тот довод, по которому уже разведены кэш и сессии
    # (ADR 0011).
    _CACHE_DB, _SESSION_DB, _SEARCH_DB = (15, 14, 13) if _TESTING else (0, 1, 7)
    CACHES = {
        'default': _redis_cache(_CACHE_DB, 'weco'),
        'sessions': _redis_cache(_SESSION_DB, 'weco-sess'),
        'search': _redis_cache(_SEARCH_DB, 'weco-search'),
    }
else:
    # Разработка без Redis — либо параллельный шаг прогона.
    CACHES = _LOCMEM_CACHES
    if not _TESTING:
        # Не журнал, а stderr: журналирование настраивается ниже по файлу и
        # на момент этой строки ещё не поднято.
        print(
            '[настройки] REDIS_URL не задан — кэш и сессии держатся в памяти '
            'процесса. Для разработки это нормально; на сервере это мина №2 '
            '(девять воркеров = девять независимых кэшей).',
            file=sys.stderr,
        )


# ─── Сессии ──────────────────────────────────────────────────────────────
#
# ⚠️ ПОЧЕМУ `cached_db`, А НЕ ЧИСТЫЙ `cache`. У Redis на сервере политика
# вытеснения `allkeys-lru` и потолок 512 МБ: под нагрузкой он выбрасывает
# ЛЮБЫЕ ключи, включая сессии. При движке `cache` источник правды — сам
# Redis, и выброшенная сессия означает разлогиненного человека посреди
# работы. У `cached_db` источник правды — база, Redis только ускоряет
# чтение: вытеснение стоит одного запроса в базу, а не потери сессии.
# Обоснование целиком — docs/adr/0011-redis-cache-and-sessions.md.
#
# ⚠️ Смены движка МИГРАЦИЙ НЕ ТРЕБУЕТ: таблица `django_session` та же самая,
# старые записи в ней остаются рабочими.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'sessions'


# ─── Слой каналов (WebSocket дуэли) ──────────────────────────────────────
#
# ⚠️ БАЗА 3, И ОНА БЫЛА ЗАРЕЗЕРВИРОВАНА ПОД ЭТО ЗАРАНЕЕ (см. таблицу баз в
# корневом CLAUDE.md). Своя база нужна по той же причине, что у сессий и у
# поиска: `cache.clear()` — это `FLUSHDB`, и живи слой каналов рядом с
# кэшем, штатный сброс кэша рвал бы все открытые дуэли.
#
# ⚠️ БЕЗ REDIS — СЛОЙ В ПАМЯТИ ПРОЦЕССА, И ЭТО ЧЕСТНО ТОЛЬКО ДЛЯ ОДНОГО
# ПРОЦЕССА. В разработке и в тестах этого достаточно; на сервере, где
# процессов несколько, InMemory означал бы, что игроки в одной дуэли не
# видят друг друга. Поэтому боевые настройки требуют REDIS_URL и падают без
# него (settings_production.py) — правило уже действует для кэша.
# ⚠️ В ТЕСТАХ СЛОЙ ВСЕГДА В ПАМЯТИ, даже когда REDIS_URL задан. Параллельный
# шаг прогона даёт восемь воркеров на один Redis, и общий слой каналов
# означал бы, что сообщения одного теста прилетают в другой. Ровно та же
# причина, по которой в память уводится кэш.
if REDIS_URL and not _TESTING:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [f'{REDIS_URL}/3']},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }


# ─── Журналы ─────────────────────────────────────────────────────────────
#
# ⚠️ ЗАЧЕМ ЭТО ВООБЩЕ ПОЯВИЛОСЬ. Своей настройки `LOGGING` в проекте не было,
# и работала настройка Django по умолчанию. В ней у консольного обработчика
# стоит фильтр `require_debug_true` — то есть на проде (`DEBUG=False`) записи
# приложения в консоль НЕ шли вовсе. Записи вроде «поставщик модели отказал»
# доезжали до stderr только запасным обработчиком Python и только начиная с
# уровня WARNING, а всё, что ниже, пропадало молча.
#
# ⚠️ ЧЕГО ЗДЕСЬ НЕТ И НЕ БУДЕТ. В журнал запрещено писать пароли, куки,
# CSRF-токены, токены приглашений и публичные токены подборок, полные
# запросы к модели и решения учеников, адрес почты в составе URL, содержимое
# загруженных файлов. Список и причины — в docs/SECURITY.md, раздел
# «Что попадает в журналы».
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {
            'format': '{levelname} {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'plain',
        },
    },
    'loggers': {
        # Свой код проекта. INFO — чтобы «что произошло» было видно, но
        # без потока отладки.
        'problems': {'handlers': ['console'], 'level': 'INFO'},
        'catalog': {'handlers': ['console'], 'level': 'INFO'},
        'teacher': {'handlers': ['console'], 'level': 'INFO'},
        'student': {'handlers': ['console'], 'level': 'INFO'},
        'game': {'handlers': ['console'], 'level': 'INFO'},
        'calendar_stub': {'handlers': ['console'], 'level': 'INFO'},
        'security': {'handlers': ['console'], 'level': 'INFO'},
        # ⚠️ `django.request` пишет трассировку пятисоток. Она нужна, и она
        # обязана быть ЗДЕСЬ, а не на экране: наружу уходит страница 500 без
        # единого технического слова (templates/500.html).
        'django.request': {'handlers': ['console'], 'level': 'ERROR',
                           'propagate': False},
        # А вот сам django.security шумит на каждую подделку хоста — оставляем
        # предупреждениями, иначе сканеры забьют журнал.
        'django.security': {'handlers': ['console'], 'level': 'WARNING',
                            'propagate': False},
    },
}

# Режим «График» (аудит чужого решения) — за СВОИМ флагом.
# ⚠️ Флаг НЕ связан с GAME_GENERATED_ENABLED: сюжеты режима — отдельное
# семейство (game/figures/), они не зависят от семнадцати архетипов, и
# включаться должны отдельным решением. По умолчанию ВЫКЛЮЧЕН — до
# визуальной приёмки преподавателем.
# Локально включается переменной окружения — чтобы посмотреть режим глазами,
# не правя настройки:  GAME_FIGURE_ENABLED=1 ./venv/bin/python manage.py runserver
GAME_FIGURE_ENABLED = os.environ.get('GAME_FIGURE_ENABLED', '') == '1'


# ⚠️ РАЗДЕЛ «ОЛИМПИАДЫ» ЗАКРЫТ ЗАГЛУШКОЙ «СКОРО» (08.09.2026, решение
# владельца). Раздел собран целиком, но показывать его публике рано.
# Персонал видит настоящие экраны и без флага — иначе разработка встанет.
OLYMPIADS_PUBLIC = os.environ.get('OLYMPIADS_PUBLIC', '0') == '1'

# ─── Бегун тестов ────────────────────────────────────────────────────────
#
# Участвует ТОЛЬКО в `manage.py test`: боевой процесс этот модуль не
# импортирует вовсе. Бегун затирает ключи поставщиков и гасит
# SMART_SEARCH_RERANK, чтобы прогон не зависел от `.env` разработчика —
# пять модулей тестов `catalog` краснели только на машине владельца, а в
# CI было зелено, и расхождение перестало быть сигналом поломки.
# Подробности и сторож — config/test_runner.py, config/tests/test_env_isolation.py.
TEST_RUNNER = 'config.test_runner.EnvIsolatedRunner'
