"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(*7+awaj76gz18jtv9(q1ejr)g05$06n5s_kpq+$vgn3t-ms$0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Наше приложение с задачами:
    'problems',
    # Этап А — Публичный каталог задач:
    'catalog',
    # Этап В1 — Кабинет ученика:
    'student',
    # Этап В2–В4 — Панель учителя:
    'teacher',
    # Этап Е — Заглушка календаря:
    'calendar_stub',
    # Этап Е — Собственный графический движок (calc2, D3 + Math.js):
    'calc2',
    # Игровая поверхность Econ Rush (публичная игра на скорость):
    'game',
]

# Используем свою модель пользователя (с ролью teacher / student).
AUTH_USER_MODEL = 'problems.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Permissions-Policy и CSP в режиме отчёта — своими настройками Django
    # их не задаёт. Подробности и обоснование — в config/security_headers.py.
    'config.security_headers.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ищем глобальные шаблоны в папке templates/ в корне проекта.
        # Это нужно чтобы переопределить admin/base_site.html (ссылка на калькулятор).
        'DIRS': [BASE_DIR / 'templates'],
        # Django 4.1+ кэширует шаблоны в памяти процесса ДАЖЕ при DEBUG=True.
        # Долго работающий runserver (особенно с --noreload) продолжает отдавать
        # СТАРЫЕ шаблоны после правок — жёсткое обновление в браузере не помогает.
        # Поэтому при DEBUG загружаем шаблоны с диска на каждый запрос.
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ] if DEBUG else [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # ⚠️ Ожидание блокировки. SQLite пускает ОДНУ запись за раз, а
        # контрольная шлёт автосохранения по ходу набора — два запроса
        # запросто оказываются в полёте вместе. По умолчанию второй падает
        # мгновенно с «database is locked», и ученик получает ошибку на
        # сохранении своей работы. Двадцать секунд ожидания снимают это
        # на локальной разработке; на проде PostgreSQL, там такого нет.
        'OPTIONS': {'timeout': 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # ⚠️ 10, а не восемь по умолчанию. Восьмизначный пароль современная
        # видеокарта перебирает быстрее, чем человек его придумывает; десять
        # — уже заметная разница, а неудобство для человека почти то же.
        # Проверяется формами Django (смена пароля); `create_user` в коде и
        # в тестах валидаторы не вызывает, поэтому фикстуры не ломаются.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Загруженные файлы (картинки, PDF, графики) будут лежать в папке media/.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Путь к xelatex для генерации PDF из подборок (Этап Б2)
XELATEX_PATH = '/Library/TeX/texbin/xelatex'

# На продакшене sentence-transformers не грузим (переопределяется в settings_production.py)
LOAD_EMBEDDINGS_MODEL = True

# ─── Семантический (смысловой) поиск ─────────────────────────────────────
#
# ⚠️ ЭТО ПРЕДОХРАНИТЕЛЬ ПРОТИВ МИНЫ №1, А НЕ НАСТРОЙКА УДОБСТВА.
# Модель эмбеддингов весит 2,12 ГБ и грузится в память КАЖДОГО рабочего
# процесса: на четырёх воркерах это 8,5 ГБ при 8 ГБ памяти сервера. Первый
# же запрос к смысловому поиску убил бы сервер. Пока модель не вынесена
# в отдельный процесс (мина №1), на боевом сервере поиск выключается.
#
# ⚠️ ПО УМОЛЧАНИЮ ВКЛЮЧЁН. Умолчание держит локальную разработку и весь
# существующий набор тестов в прежнем поведении: выключить — это осознанное
# действие через окружение, а не то, что случается само.
#
# Выключенный флаг означает ДЕГРАДАЦИЮ, А НЕ ОТКАЗ (правило 6.13
# docs/EMBEDDINGS.md): страница поиска отвечает 200, ищет по словам и честно
# говорит об этом человеку. Ни пятисотки, ни вечного ожидания.
#
# ⚠️ Флаг обязан проверяться ДО импорта sentence_transformers, а не после.
# Проверка после импорта бесполезна: 2,12 ГБ уже в памяти. Это стережёт
# тест, который смотрит на sys.modules.
SEMANTIC_SEARCH_ENABLED = (
    os.environ.get('SEMANTIC_SEARCH_ENABLED', '1').strip().lower()
    not in ('0', 'false', 'no', 'off', '')
)

# ─── Сервис кодирования запросов (С4) ────────────────────────────────────
#
# Адрес соседнего контейнера во внутренней сети Docker. Наружу этот порт
# не публикуется (в compose у сервиса нет секции ports) — снаружи его
# достать нельзя, и это проверяется вручную по docs/SERVER.md.
#
# ⚠️ ПУСТОЕ ЗНАЧЕНИЕ = «СЕРВИСА НЕТ», А НЕ ОШИБКА. Локальная разработка и
# прогон тестов идут без поднятого сервиса, и поиск обязан деградировать
# до поиска по словам, а не падать. Умолчание указывает на имя сервиса в
# compose, потому что именно там он и живёт.
SEARCH_SERVICE_URL = os.environ.get(
    'SEARCH_SERVICE_URL', 'http://search:8001').strip()

# ⚠️ ТАЙМАУТ КОРОТКИЙ НАМЕРЕННО. Он стоит на пути ЖИВОГО поискового
# запроса: пока он тикает, человек смотрит на крутилку. Лучше через пять
# секунд честно отдать поиск по словам, чем через минуту — то же самое.
# Первый запрос после старта сервиса дольше (модель грузится с диска), и
# он законно упадёт в деградацию — это разовая цена, а не поломка.
SEARCH_SERVICE_TIMEOUT = float(
    os.environ.get('SEARCH_SERVICE_TIMEOUT', '5').strip() or 5)

# Этап В1 — Кабинет ученика: URL для входа и редирект по умолчанию.
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/student/'  # переопределяется в RoleBasedLoginView
LOGOUT_REDIRECT_URL = '/login/'

# Econ Rush: сгенерированные вопросы (game/generators/) участвуют в выдаче.
# На проде выключено в settings_production.py, пока преподаватель не проверил
# превью и не принял решение о выкатке.
GAME_GENERATED_ENABLED = True


# ─── Кэш и сессии: Redis ─────────────────────────────────────────────────
#
# ⚠️ ЗАЧЕМ ЭТО ПОЯВИЛОСЬ. До 2026-08-21 здесь стоял один `LocMemCache` —
# память ОДНОГО процесса. Пока сайт жил в один процесс, это работало.
# На боевом сервере воркеров девять, и тот же словарь означал бы девять
# независимых кэшей: попадание примерно один раз из девяти, счётчик
# неудачных входов свой у каждого воркера (то есть попыток до запрета
# в девять раз больше), а сброс кэша доходил бы до одного воркера из девяти.
# Это «мина №2» из разбора боевого сервера.
#
# ⚠️ РАСКЛАДКА БАЗ REDIS — СОГЛАШЕНИЕ ПРОЕКТА, МЕНЯТЬ ТОЛЬКО ОСОЗНАННО:
#     БД 0  — кэш приложения (алиас `default`)
#     БД 1  — сессии (алиас `sessions`)
#     БД 2  — брокер Celery (зарезервировано, сейчас не используется)
#     БД 3  — channel layer для WebSocket (зарезервировано)
#     БД 14 — сессии во время прогона тестов
#     БД 15 — кэш во время прогона тестов
#
# ⚠️ ПОЧЕМУ КЭШ И СЕССИИ В РАЗНЫХ БАЗАХ. `cache.clear()` у Redis-бэкенда
# Django — это FLUSHDB: он вычищает базу Redis ЦЕЛИКОМ, а не только ключи
# своего алиаса. `cache.clear()` вызывается в 18 местах набора тестов и
# может понадобиться на сервере. Лежи сессии в той же базе — любой сброс
# кэша разлогинивал бы всех до одного. Разные базы + разные алиасы —
# единственное, что делает это невозможным по устройству, а не по договорённости.
#
# ⚠️ ПОЧЕМУ ТЕСТЫ УВОДЯТСЯ НА 15 и 14. Тесты зовут `cache.clear()`. Если
# разработчик держит в `REDIS_URL` адрес рабочего Redis, прогон вычистил бы
# его рабочий кэш. Отдельные номера баз делают это безвредным.
import os
import sys

# redis://[:пароль@]хост:порт — БЕЗ номера базы, его дописывает `_redis_cache`.
# ⚠️ Пароль внутри URL обязан быть percent-encoded: символы @ : / # ? ломают
# разбор адреса. `deploy/env.example` велит генерировать пароли только из
# латиницы и цифр — тогда кодировать нечего. Разбор проверяется ниже.
REDIS_URL = os.environ.get('REDIS_URL', '').strip()

# Прогон тестов узнаётся по argv, а не по переменной окружения: переменную
# забывают выставить ровно тогда, когда это важнее всего.
_TESTING = 'test' in sys.argv


def _redis_cache(db_index, prefix):
    """Один алиас кэша в отдельной базе Redis."""
    return {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'{REDIS_URL}/{db_index}',
        'KEY_PREFIX': prefix,
        'TIMEOUT': 300,
    }


if REDIS_URL:
    # Адрес разбирается ЗДЕСЬ, а не при первом обращении к кэшу: сломанный
    # URL должен валить старт с внятным текстом, а не отдавать пятисотку
    # первому посетителю.
    from urllib.parse import urlsplit as _urlsplit

    _parts = _urlsplit(REDIS_URL)
    if _parts.scheme not in ('redis', 'rediss', 'unix') or not _parts.netloc:
        raise ValueError(
            'REDIS_URL не разбирается как адрес Redis. Ожидается '
            'redis://хост:порт или redis://:пароль@хост:порт. Если в пароле '
            'есть @ : / # или ?, его надо percent-encode (urllib.parse.quote).'
        )
    del _parts, _urlsplit

# ⚠️ ПАРАЛЛЕЛЬНЫЙ ШАГ ПРОГОНА УВОДИТ КЭШ В ПАМЯТЬ ПРОЦЕССА, И ЭТО ГЛАВНОЕ
# МЕСТО ВСЕЙ ЗАТЕИ С `--parallel`.
#
# Django при `--parallel` даёт каждому воркеру СВОЮ тестовую базу. А Redis
# остаётся один на всех: восемь воркеров писали бы в одну базу 15, и первый
# же `cache.clear()` (их 18 в наборе) обнулял бы кэш остальным семи посреди
# их работы. Симптом был бы худшим из возможных — тесты падают случайно и
# не воспроизводятся поодиночке.
#
# ⚠️ РАЗДЕЛИТЬ ПРЕФИКСОМ КЛЮЧЕЙ НЕЛЬЗЯ. `cache.clear()` у Redis-бэкенда
# Django — это `FLUSHDB`: он чистит базу ЦЕЛИКОМ и `KEY_PREFIX` не смотрит.
# Префикс развёл бы ключи, но не спас бы от сброса.
#
# ⚠️ ОТДЕЛЬНОЙ БАЗЫ REDIS НА ВОРКЕРА ТОЖЕ НЕ ХВАТАЕТ. Баз всего 16; 0–1 под
# боевые, 2–3 зарезервированы. На машине владельца 8 ядер, то есть
# `--parallel auto` даёт 8 воркеров и потребовал бы 16 баз только под тесты.
# Схема, которая ломается от покупки нового ноутбука, — не схема.
#
# Поэтому: на параллельном шаге кэш у каждого воркера свой, в его памяти.
# Изоляция получается по устройству процесса, а не по договорённости.
# Тесты, которым нужен НАСТОЯЩИЙ Redis, помечены `@tag('serial')` и идут
# вторым шагом, где Redis снова настоящий. Подробности — docs/TESTING.md.
_LOCAL_TEST_CACHE = os.environ.get('QLS_TEST_LOCAL_CACHE', '') == '1'

# Два РАЗНЫХ `LOCATION` обязательны: одинаковое имя у LocMemCache — это один
# и тот же склад под двумя вывесками, и тогда `cache.clear()` снова уносил бы
# сессии, только уже локально.
_LOCMEM_CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qls-default',
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qls-sessions',
    },
    # Векторы поисковых запросов (С4). Своё место по той же причине, что и
    # у сессий: они дорого достаются и не должны исчезать от сброса кэша.
    'search': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qls-search',
    },
}

if REDIS_URL and not (_TESTING and _LOCAL_TEST_CACHE):
    # ⚠️ У ПОИСКА СВОЯ БАЗА (7), И ЭТО НЕ ПЕДАНТИЗМ. Вектор запроса считает
    # модель — это самая дорогая единица данных в проекте. В общей базе с
    # обычным кэшем любой штатный `cache.clear()` (а он же FLUSHDB) уносил
    # бы их вместе с мелочью, и следующая волна запросов заново будила бы
    # модель. Ровно тот довод, по которому уже разведены кэш и сессии
    # (ADR 0011).
    _CACHE_DB, _SESSION_DB, _SEARCH_DB = (15, 14, 13) if _TESTING else (0, 1, 7)
    CACHES = {
        'default': _redis_cache(_CACHE_DB, 'weco'),
        'sessions': _redis_cache(_SESSION_DB, 'weco-sess'),
        'search': _redis_cache(_SEARCH_DB, 'weco-search'),
    }
else:
    # Разработка без Redis — либо параллельный шаг прогона.
    CACHES = _LOCMEM_CACHES
    if not _TESTING:
        # Не журнал, а stderr: журналирование настраивается ниже по файлу и
        # на момент этой строки ещё не поднято.
        print(
            '[настройки] REDIS_URL не задан — кэш и сессии держатся в памяти '
            'процесса. Для разработки это нормально; на сервере это мина №2 '
            '(девять воркеров = девять независимых кэшей).',
            file=sys.stderr,
        )


# ─── Сессии ──────────────────────────────────────────────────────────────
#
# ⚠️ ПОЧЕМУ `cached_db`, А НЕ ЧИСТЫЙ `cache`. У Redis на сервере политика
# вытеснения `allkeys-lru` и потолок 512 МБ: под нагрузкой он выбрасывает
# ЛЮБЫЕ ключи, включая сессии. При движке `cache` источник правды — сам
# Redis, и выброшенная сессия означает разлогиненного человека посреди
# работы. У `cached_db` источник правды — база, Redis только ускоряет
# чтение: вытеснение стоит одного запроса в базу, а не потери сессии.
# Обоснование целиком — docs/adr/0011-redis-cache-and-sessions.md.
#
# ⚠️ Смены движка МИГРАЦИЙ НЕ ТРЕБУЕТ: таблица `django_session` та же самая,
# старые записи в ней остаются рабочими.
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'sessions'


# ─── Журналы ─────────────────────────────────────────────────────────────
#
# ⚠️ ЗАЧЕМ ЭТО ВООБЩЕ ПОЯВИЛОСЬ. Своей настройки `LOGGING` в проекте не было,
# и работала настройка Django по умолчанию. В ней у консольного обработчика
# стоит фильтр `require_debug_true` — то есть на проде (`DEBUG=False`) записи
# приложения в консоль НЕ шли вовсе. Записи вроде «поставщик модели отказал»
# доезжали до stderr только запасным обработчиком Python и только начиная с
# уровня WARNING, а всё, что ниже, пропадало молча.
#
# ⚠️ ЧЕГО ЗДЕСЬ НЕТ И НЕ БУДЕТ. В журнал запрещено писать пароли, куки,
# CSRF-токены, токены приглашений и публичные токены подборок, полные
# запросы к модели и решения учеников, адрес почты в составе URL, содержимое
# загруженных файлов. Список и причины — в docs/SECURITY.md, раздел
# «Что попадает в журналы».
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {
            'format': '{levelname} {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'plain',
        },
    },
    'loggers': {
        # Свой код проекта. INFO — чтобы «что произошло» было видно, но
        # без потока отладки.
        'problems': {'handlers': ['console'], 'level': 'INFO'},
        'catalog': {'handlers': ['console'], 'level': 'INFO'},
        'teacher': {'handlers': ['console'], 'level': 'INFO'},
        'student': {'handlers': ['console'], 'level': 'INFO'},
        'game': {'handlers': ['console'], 'level': 'INFO'},
        'calendar_stub': {'handlers': ['console'], 'level': 'INFO'},
        'security': {'handlers': ['console'], 'level': 'INFO'},
        # ⚠️ `django.request` пишет трассировку пятисоток. Она нужна, и она
        # обязана быть ЗДЕСЬ, а не на экране: наружу уходит страница 500 без
        # единого технического слова (templates/500.html).
        'django.request': {'handlers': ['console'], 'level': 'ERROR',
                           'propagate': False},
        # А вот сам django.security шумит на каждую подделку хоста — оставляем
        # предупреждениями, иначе сканеры забьют журнал.
        'django.security': {'handlers': ['console'], 'level': 'WARNING',
                            'propagate': False},
    },
}
