"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(*7+awaj76gz18jtv9(q1ejr)g05$06n5s_kpq+$vgn3t-ms$0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Наше приложение с задачами:
    'problems',
    # Этап А — Публичный каталог задач:
    'catalog',
    # Этап В1 — Кабинет ученика:
    'student',
    # Этап В2–В4 — Панель учителя:
    'teacher',
    # Этап Е — Заглушка календаря:
    'calendar_stub',
    # Этап Е — Собственный графический движок (calc2, D3 + Math.js):
    'calc2',
    # Игровая поверхность Econ Rush (публичная игра на скорость):
    'game',
]

# Используем свою модель пользователя (с ролью teacher / student).
AUTH_USER_MODEL = 'problems.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Permissions-Policy и CSP в режиме отчёта — своими настройками Django
    # их не задаёт. Подробности и обоснование — в config/security_headers.py.
    'config.security_headers.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ищем глобальные шаблоны в папке templates/ в корне проекта.
        # Это нужно чтобы переопределить admin/base_site.html (ссылка на калькулятор).
        'DIRS': [BASE_DIR / 'templates'],
        # Django 4.1+ кэширует шаблоны в памяти процесса ДАЖЕ при DEBUG=True.
        # Долго работающий runserver (особенно с --noreload) продолжает отдавать
        # СТАРЫЕ шаблоны после правок — жёсткое обновление в браузере не помогает.
        # Поэтому при DEBUG загружаем шаблоны с диска на каждый запрос.
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ] if DEBUG else [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # ⚠️ Ожидание блокировки. SQLite пускает ОДНУ запись за раз, а
        # контрольная шлёт автосохранения по ходу набора — два запроса
        # запросто оказываются в полёте вместе. По умолчанию второй падает
        # мгновенно с «database is locked», и ученик получает ошибку на
        # сохранении своей работы. Двадцать секунд ожидания снимают это
        # на локальной разработке; на проде PostgreSQL, там такого нет.
        'OPTIONS': {'timeout': 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # ⚠️ 10, а не восемь по умолчанию. Восьмизначный пароль современная
        # видеокарта перебирает быстрее, чем человек его придумывает; десять
        # — уже заметная разница, а неудобство для человека почти то же.
        # Проверяется формами Django (смена пароля); `create_user` в коде и
        # в тестах валидаторы не вызывает, поэтому фикстуры не ломаются.
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Загруженные файлы (картинки, PDF, графики) будут лежать в папке media/.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Путь к xelatex для генерации PDF из подборок (Этап Б2)
XELATEX_PATH = '/Library/TeX/texbin/xelatex'

# На продакшене sentence-transformers не грузим (переопределяется в settings_production.py)
LOAD_EMBEDDINGS_MODEL = True

# Этап В1 — Кабинет ученика: URL для входа и редирект по умолчанию.
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/student/'  # переопределяется в RoleBasedLoginView
LOGOUT_REDIRECT_URL = '/login/'

# Econ Rush: сгенерированные вопросы (game/generators/) участвуют в выдаче.
# На проде выключено в settings_production.py, пока преподаватель не проверил
# превью и не принял решение о выкатке.
GAME_GENERATED_ENABLED = True


# ─── Кэш: счётчики ограничения частоты ───────────────────────────────────
#
# ⚠️ СЕГОДНЯ ЭТО ПАМЯТЬ ПРОЦЕССА, И ЭТО НАДО ЗНАТЬ ЧЕСТНО. `LocMemCache`
# живёт внутри одного процесса: счётчик неудачных входов не переживает
# перезапуск, а при нескольких воркерах у каждого он свой. На бесплатном
# хостинге процесс один, поэтому ограничение работает; после переезда
# Redis подключается сменой ЭТОГО словаря — код в `problems/ratelimit.py`
# знает только `django.core.cache.cache` и правки не потребует.
#
# Имя `LOCATION` задано явно: без него два разных места кода могут получить
# разные экземпляры кэша и не увидеть счётчиков друг друга.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qls-default',
    },
}


# ─── Журналы ─────────────────────────────────────────────────────────────
#
# ⚠️ ЗАЧЕМ ЭТО ВООБЩЕ ПОЯВИЛОСЬ. Своей настройки `LOGGING` в проекте не было,
# и работала настройка Django по умолчанию. В ней у консольного обработчика
# стоит фильтр `require_debug_true` — то есть на проде (`DEBUG=False`) записи
# приложения в консоль НЕ шли вовсе. Записи вроде «поставщик модели отказал»
# доезжали до stderr только запасным обработчиком Python и только начиная с
# уровня WARNING, а всё, что ниже, пропадало молча.
#
# ⚠️ ЧЕГО ЗДЕСЬ НЕТ И НЕ БУДЕТ. В журнал запрещено писать пароли, куки,
# CSRF-токены, токены приглашений и публичные токены подборок, полные
# запросы к модели и решения учеников, адрес почты в составе URL, содержимое
# загруженных файлов. Список и причины — в docs/SECURITY.md, раздел
# «Что попадает в журналы».
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {
            'format': '{levelname} {asctime} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'plain',
        },
    },
    'loggers': {
        # Свой код проекта. INFO — чтобы «что произошло» было видно, но
        # без потока отладки.
        'problems': {'handlers': ['console'], 'level': 'INFO'},
        'catalog': {'handlers': ['console'], 'level': 'INFO'},
        'teacher': {'handlers': ['console'], 'level': 'INFO'},
        'student': {'handlers': ['console'], 'level': 'INFO'},
        'game': {'handlers': ['console'], 'level': 'INFO'},
        'calendar_stub': {'handlers': ['console'], 'level': 'INFO'},
        'security': {'handlers': ['console'], 'level': 'INFO'},
        # ⚠️ `django.request` пишет трассировку пятисоток. Она нужна, и она
        # обязана быть ЗДЕСЬ, а не на экране: наружу уходит страница 500 без
        # единого технического слова (templates/500.html).
        'django.request': {'handlers': ['console'], 'level': 'ERROR',
                           'propagate': False},
        # А вот сам django.security шумит на каждую подделку хоста — оставляем
        # предупреждениями, иначе сканеры забьют журнал.
        'django.security': {'handlers': ['console'], 'level': 'WARNING',
                            'propagate': False},
    },
}
