# Generated by Django 4.2.30 on 2026-07-11 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0019_add_solution_ai_extracted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('options', models.JSONField(verbose_name='Варианты ответа')),
                ('correct_index', models.PositiveSmallIntegerField(verbose_name='Индекс правильного (0-based)')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, verbose_name='Сложность (1–5)')),
                ('topics', models.JSONField(blank=True, default=list, verbose_name='Темы (названия)')),
                ('lang', models.CharField(default='ru', max_length=2, verbose_name='Язык вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Собран')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_question', to='problems.problem', verbose_name='Задача-источник')),
            ],
            options={
                'verbose_name': 'Игровой вопрос',
                'verbose_name_plural': 'Игровые вопросы',
                'indexes': [models.Index(fields=['lang', 'difficulty'], name='game_gamequ_lang_fc3b61_idx')],
            },
        ),
    ]
