# Generated by Django 4.2.30 on 2026-07-11 14:10

from django.db import migrations, models
import django.db.models.deletion


def clear_pool(apps, schema_editor):
    """Пул — пересобираемый кэш: перед сменой схемы просто очищаем его.
    После миграции запустить `manage.py build_game_pool`."""
    apps.get_model('game', 'GameQuestion').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_add_solution_ai_extracted'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_pool, migrations.RunPython.noop),
        migrations.AddField(
            model_name='gamequestion',
            name='correct_indices',
            field=models.JSONField(blank=True, null=True, verbose_name='Индексы правильных (multi)'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='correct_value',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Точный числовой ответ (numeric)'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='problems.problempart', verbose_name='Подпункт-источник'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='question_type',
            field=models.CharField(choices=[('boolean', 'Данетка'), ('single', 'Один из'), ('multi', 'Несколько из'), ('numeric', 'Числовой')], db_index=True, default='single', max_length=10, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Этап олимпиады'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='correct_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Индекс правильного (0-based)'),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='problems.problem', verbose_name='Задача-источник'),
        ),
        migrations.AddIndex(
            model_name='gamequestion',
            index=models.Index(fields=['lang', 'question_type'], name='game_gamequ_lang_c5c2d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamequestion',
            constraint=models.UniqueConstraint(fields=('problem', 'part'), name='uniq_gq_problem_part'),
        ),
    ]
