# Generated by Django 4.2.30 on 2026-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamequestion_correct_indices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Единица ответа'),
        ),
    ]
