# Generated by Django 4.2.30 on 2026-07-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_sourcereference_year'),
        ('game', '0003_gamequestion_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='gen_params',
            field=models.JSONField(blank=True, null=True, verbose_name='Параметры генерации'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='gen_solution',
            field=models.TextField(blank=True, default='', verbose_name='Пошаговое решение (KaTeX)'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='generator_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Ключ генератора (архетип)'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='is_generated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Сгенерирован'),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_questions', to='problems.problem', verbose_name='Задача-источник'),
        ),
    ]
