# Generated by Django 4.2.30 on 2026-07-16 00:03

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamequestion_gen_params_gamequestion_gen_solution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=game.models.make_result_code, max_length=16, unique=True, verbose_name='Код ссылки')),
                ('mode', models.CharField(max_length=16, verbose_name='Режим')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Счёт')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name='Верных')),
                ('total_count', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('max_combo', models.PositiveSmallIntegerField(default=1, verbose_name='Макс. множитель')),
                ('ended_reason', models.CharField(default='time', max_length=8, verbose_name='Чем кончился')),
                ('topic_breakdown', models.JSONField(blank=True, default=list, verbose_name='Разбивка по темам')),
                ('difficulty_breakdown', models.JSONField(blank=True, default=list, verbose_name='Разбивка по сложности')),
                ('score_curve', models.JSONField(blank=True, default=list, verbose_name='Кривая счёта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сыгран')),
            ],
            options={
                'verbose_name': 'Результат забега',
                'verbose_name_plural': 'Результаты забегов',
                'ordering': ['-created_at'],
            },
        ),
    ]
