# Generated by Django 4.2.30 on 2026-07-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='figure',
            field=models.JSONField(blank=True, null=True, verbose_name='Параметры графика'),
        ),
    ]
