# Generated by Django 4.2.30 on 2026-07-26 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_sourcereference_year'),
        ('game', '0006_gamequestion_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchetypeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown', models.PositiveIntegerField(default=0, verbose_name='Показов')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='Верных')),
                ('wrong', models.PositiveIntegerField(default=0, verbose_name='Неверных')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='Пропусков')),
                ('total_ms', models.BigIntegerField(default=0, verbose_name='Сумма времени ответов (мс)')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('generator_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ архетипа')),
            ],
            options={
                'verbose_name': 'Статистика архетипа',
                'verbose_name_plural': 'Статистика архетипов',
            },
        ),
        migrations.CreateModel(
            name='BankQuestionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown', models.PositiveIntegerField(default=0, verbose_name='Показов')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='Верных')),
                ('wrong', models.PositiveIntegerField(default=0, verbose_name='Неверных')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='Пропусков')),
                ('total_ms', models.BigIntegerField(default=0, verbose_name='Сумма времени ответов (мс)')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='problems.problempart', verbose_name='Подпункт')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Статистика вопроса банка',
                'verbose_name_plural': 'Статистика вопросов банка',
            },
        ),
        migrations.AddConstraint(
            model_name='bankquestionstat',
            constraint=models.UniqueConstraint(fields=('problem', 'part'), name='uniq_bank_stat_problem_part'),
        ),
    ]
