# Generated by Django 4.2.30 on 2026-07-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_archetypestat_bankquestionstat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='source_group',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Группа источников'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID источника'),
        ),
    ]
