# Generated by Django 4.2.30 on 2026-07-26 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0008_gamequestion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results', to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=game.models.make_code, max_length=16, unique=True, verbose_name='Код')),
                ('mode', models.CharField(max_length=16, verbose_name='Режим')),
                ('kind', models.CharField(choices=[('daily', 'Вызов дня'), ('custom', 'Набор учителя'), ('duel', 'Дуэль')], db_index=True, default='custom', max_length=8, verbose_name='Происхождение')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('question_ids', models.JSONField(default=list, verbose_name='Вопросы (по порядку)')),
                ('filter_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок фильтра')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='Открыт с')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт с')),
                ('attempts_allowed', models.PositiveSmallIntegerField(default=1, verbose_name='Попыток')),
                ('day', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата вызова дня')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Набор вопросов',
                'verbose_name_plural': 'Наборы вопросов',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.gameset', verbose_name='Набор'),
        ),
        migrations.AddConstraint(
            model_name='gameset',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'daily')), fields=('kind', 'mode', 'day'), name='uniq_daily_set_per_mode'),
        ),
    ]
