# Generated by Django 4.2.30 on 2026-07-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameset'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='question_outcomes',
            field=models.JSONField(blank=True, default=list, verbose_name='Исходы по вопросам'),
        ),
    ]
