# Generated by Django 4.2.30 on 2026-07-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gameresult_question_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='question_type',
            field=models.CharField(choices=[('boolean', 'Данетка'), ('single', 'Один из'), ('multi', 'Несколько из'), ('numeric', 'Числовой'), ('figure_choice', 'Выбор чертежа')], db_index=True, default='single', max_length=16, verbose_name='Тип вопроса'),
        ),
    ]
