# Generated by Django 4.2.30 on 2026-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_figure_choice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='figure_ref',
            field=models.JSONField(blank=True, null=True, verbose_name='Эталонный чертёж (аудит)'),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='question_type',
            field=models.CharField(choices=[('boolean', 'Данетка'), ('single', 'Один из'), ('multi', 'Несколько из'), ('numeric', 'Числовой'), ('figure_choice', 'Выбор чертежа (не выдаётся)'), ('figure_audit', 'Аудит чужого решения')], db_index=True, default='single', max_length=16, verbose_name='Тип вопроса'),
        ),
    ]
