# Generated by Django 5.2.17 on 2026-09-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_figure_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='tag_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='ID тегов'),
        ),
    ]
