# Generated by Django 5.2.17 on 2026-09-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_result_ranked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='ended_reason',
            field=models.CharField(default='time', max_length=16, verbose_name='Чем кончился'),
        ),
    ]
